import {TYPES} from './state.js';
import {dist,length,pointOnRoute} from './world.js';
export function spec(type){return TYPES.find(t=>t.name===type)||TYPES[0]}
function touches(r,b){return r.points.some(p=>dist(p,b)<b.r+28)}
export function route(s,a,b){let best=null;for(const r of s.roads){if(!touches(r,a)||!touches(r,b))continue;const forward=dist(r.points[0],a)<=dist(r.points.at(-1),a);const pts=forward?r.points:[...r.points].reverse();const d=length(pts)+dist(a,pts[0])+dist(pts.at(-1),b);if(!best||d<best.distance)best={points:[{x:a.x,y:a.y},...pts,{x:b.x,y:b.y}],distance:d}}return best}
export function newContract(s,shop){if(shop.contract)return;const f=spec(shop.need),qty=Math.max(2,Math.min(12,Math.round((3+Math.random()*3+(shop.level-1))*f.qty)));const reward=Math.round(f.price*qty*(1.7+shop.level*.2));shop.contract={id:s.contractId++,type:shop.need,qty,remaining:qty,reward,expires:65+shop.level*10,initial:qty,urgent:Math.random()>.72}}
export function upgrade(s,b,n){if(b.kind==='factory'){const price=n===1?120*b.level:n===2?180+(b.max-4)/2*70:n===3?220*(b.loading+1):300*(b.logistics+1);if(s.cash<price)return false;if(n===1&&b.level<3)b.level++;else if(n===2&&b.max<14)b.max+=2;else if(n===3&&b.loading<2)b.loading++;else if(n===4&&b.logistics<2)b.logistics++;else return false;s.cash-=price;return true}const price=220*b.level;if(b.kind==='shop'&&b.level<3&&s.cash>=price){s.cash-=price;b.level++;b.max=Math.min(14,b.max+2);b.demand=Math.min(14,b.demand+2);return true}return false}
export function updateEconomy(s,dt,flash){s.weekTime+=dt;s.nextBuilding-=dt;if(s.weekTime>=32){s.week++;s.weekTime=0;s.roadBudget+=5;s.cash+=35+s.week*4;for(const b of s.buildings)if(b.kind==='shop'){b.demand=Math.min(14,b.demand+1+Math.random()*2);if(!b.contract)newContract(s,b)}flash(`Week ${s.week} • +5 roads • £${35+s.week*4}`)}
 if(s.nextBuilding<=0){s.nextBuilding=Math.max(14,24-s.week*.35);if(s.buildings.length<16){const shops=s.buildings.filter(b=>b.kind==='shop'),fs=s.buildings.filter(b=>b.kind==='factory');const target=Math.random()<.5?shops[Math.floor(Math.random()*shops.length)]:fs[Math.floor(Math.random()*fs.length)];if(target)import('./world.js').then(w=>w.spawn(s,target.kind==='shop'?'factory':'shop',target.kind==='shop'?target.need:target.type))}}
 for(const b of s.buildings){if(b.kind==='factory'){const f=spec(b.type);b.production+=dt*.52*b.level*f.speed;if(b.production>=1&&b.stock<b.max){const n=Math.floor(b.production);b.production-=n;b.stock=Math.min(b.max,b.stock+n)}}else{b.demand=Math.min(14,b.demand+dt*(.05+s.week*.003));if(!b.contract&&Math.random()<dt*.012)newContract(s,b);if(b.contract){b.contract.expires-=dt;if(b.contract.expires<=0){s.reputation=Math.max(0,s.reputation-4);b.contract=null;flash('Contract expired • reputation -4')}}}}
 for(const f of s.buildings.filter(b=>b.kind==='factory')){const shops=s.buildings.filter(b=>b.kind==='shop'&&b.need===f.type&&b.demand>0);let choice=null,best=Infinity;for(const shop of shops){const r=route(s,f,shop);if(r&&r.distance<best){best=r.distance;choice=shop}}const shop=choice;if(!shop||f.stock<=0)continue;if(Math.random()<dt*(1.4+f.level*.35)){const r=route(s,f,shop);if(!r)continue;f.stock--;shop.demand--;const sp=spec(f.type);const value=Math.round(sp.price*sp.value*(1+Math.min(1.2,r.distance/650)*.45)*(1+(f.level-1)*.08+f.loading*.1)*(1+f.logistics*.05));const contract=shop.contract?.type===f.type?shop.contract:null;s.trucks.push({route:r.points,t:0,speed:.085*sp.speed*(1+(f.level-1)*.08+f.loading*.04),value,to:shop,source:f,contractId:contract?.id||0,longDistance:r.distance>650,wait:0})}}
 for(const t of s.trucks){const p=pointOnRoute(t.route,t.t);let blocked=false;for(const o of s.trucks){if(o===t)continue;const q=pointOnRoute(o.route,o.t);if(dist(p,q)<28&&o.t>t.t){blocked=true;break}}if(blocked){t.wait=Math.min(2,t.wait+dt);continue}t.t+=dt*t.speed;if(t.t>=1){s.cash+=t.value;s.deliveryIncome+=t.value;s.orders++;s.deliveredBy[t.source.type]=(s.deliveredBy[t.source.type]||0)+1;t.to.served++;if(t.longDistance)s.longContracts++;if(t.contractId&&t.to.contract?.id===t.contractId){const c=t.to.contract;c.remaining--;if(c.remaining<=0){const bonus=c.urgent?Math.round(c.reward*.18):0;s.cash+=c.reward+bonus;s.reputation=Math.min(100,s.reputation+2);t.to.contract=null;flash(`Contract complete • £${c.reward+bonus}`)}}t.dead=true}}
s.trucks=s.trucks.filter(t=>!t.dead);s.congestion=Math.min(1,(s.trucks.length+s.trucks.filter(t=>t.wait>0).length*1.5)/Math.max(3,s.roads.length*2));const reduction=s.trucks.reduce((n,t)=>n+(t.source?.logistics||0),0)/Math.max(1,s.trucks.length);s.cash-=s.roads.length*dt*.055*(1+s.congestion*Math.max(.55,1-reduction*.12));const g=s.goals[s.objective];if(g&&g.done(s))s.objective=Math.min(5,s.objective+1);if(s.cash<=0){s.cash=0;s.gameOver=true}}
