import {freshState,hydrate,serialise,TYPES} from './state.js';
import {seed,nearestBuilding,buildingAtPoint,roadBuildingTarget,nearestRoad,roadTarget,roadPreview,addRoad,editRoadSegment,roadSegmentAtPoint,roadEndpointAtPoint,roadEndpointPreview,editRoadEndpoint,dist,buildingCost,buildingUnlock,canBuild,canPlaceBuildingAt,placeBuilding} from './world.js';
import {updateEconomy,upgrade,newContract,research,researchCost} from './economy.js';
import {render,setPreview,resizeRenderer,controlCamera,screenToWorld,panScreen,zoomAtScreen,resetCamera} from './render.js';

const GAME_VERSION='1.0.32';
const CHANGELOG=[
  {version:'1.0.32',date:'1 Oct 2026',items:['Hardened road junction graph construction so duplicate discovered edges cannot inflate junction degrees or confuse routing.','Traffic junction reservations now use deterministic simulation time and automatically expire instead of relying on browser timing.','Stabilised 3-way and 4-way junction visuals by ordering approach geometry consistently before drawing curved lane transitions.']},
  {version:'1.0.31',date:'1 Oct 2026',items:['Built the first real warehouse supply-chain pipeline: factories feed connected warehouses before goods are distributed to shops.','Warehouse inventory now drives physical warehouse-to-shop truck deliveries, so warehouses are a meaningful part of the logistics loop instead of passive storage.','Added simple warehouse upgrades for storage capacity and logistics without adding manual truck management.']},
  {version:'1.0.30',date:'30 Sep 2026',items:['Fixed mobile panels so building, research and company UIs use the available screen width instead of staying as narrow centred cards.','Fixed the Upgrade shop control so it only appears for actual shop buildings and cannot be forced visible by the mobile layout CSS.']},
  {version:'1.0.29',date:'30 Sep 2026',items:['Improved same-lane truck following with progressive speed reduction and dynamic safe gaps.','Traffic queues now brake smoothly instead of bunching into abrupt stop-and-go chains.']},
  {version:'1.0.28',date:'30 Sep 2026',items:['Completed the road traffic control pass with progressive braking before junction conflicts instead of instant stopping.','Added visible lane-correct stop/approach markings and truck brake-light states for yielding, approaching and stopped traffic.']},
  {version:'1.0.27',date:'30 Sep 2026',items:['Fixed the mobile building palette so horizontal swipes scroll through all building cards instead of being captured as a drag.','Kept drag-and-drop building placement by treating vertical movement toward the map as the drag gesture.']},
  {version:'1.0.26',date:'30 Sep 2026',items:['Fixed junction movement classification so straight-through traffic is treated as straight instead of being misclassified by direction vectors.','Added visible junction control lines aligned to the active left-hand traffic lane and made spawned trucks explicitly lane-aware.']},
  {version:'1.0.25',date:'30 Sep 2026',items:['Hardened traffic right-of-way with explicit junction reservations so conflicting movements cannot enter the same junction together.','Added UK-style left-hand traffic lane positioning and crossing protection for routes whose junction point is not an explicit route vertex.']},
  {version:'1.0.23',date:'30 Sep 2026',items:['Fixed road drawing from buildings so the road connection point dynamically faces the destination building instead of starting on the wrong side.','Expanded building connection snapping and endpoint tolerance so roads can reliably reach nearby building facades without being blocked prematurely.']},
  {version:'1.0.22',date:'30 Sep 2026',items:['Improved mobile building and road hit areas so taps do not require pixel-perfect placement.','Added short access aprons between connected roads and building facades for a cleaner visual transition.']},
  {version:'1.0.21',date:'30 Sep 2026',items:['Fixed road-to-building connection geometry so road endpoints terminate on the actual rectangular building footprint instead of an oversized circular radius.','Improved road attachment tolerance so existing roads reliably connect to factory, shop and warehouse facades.']},
  {version:'1.0.20',date:'30 Sep 2026',items:['Fixed road deletion to execute immediately on touch/click instead of waiting for pointer-up.','Road deletion now uses the exact road hit detected on pointer-down, preventing mobile pointer-capture timing from cancelling the delete.']},
  {version:'1.0.19',date:'30 Sep 2026',items:['Fixed road deletion so tapping a road removes the whole road instead of leaving fragments.','Removed road splitting from the editor and simplified mobile road deletion to a single tap.']},
  {version:'1.0.18',date:'30 Sep 2026',items:['Fixed startup failure caused by invalid JavaScript escape syntax in the game source.','Kept renderer startup signalling while removing the malformed source sequence.']},
  {version:'1.0.17',date:'30 Sep 2026',items:['Hardened startup so the loading screen waits for the actual 3D renderer instead of probing WebGL first.','Added a renderer-ready signal so the map cannot be hidden before the game has drawn its first frame.']},
  {version:'1.0.16',date:'30 Sep 2026',items:['Hardened traffic dispatch so saturated roads stop spawning unnecessary trucks.','Preserved multi-road junction classification for near-touching and endpoint-to-road connections.']},
  {version:'1.0.15',date:'30 Sep 2026',items:['Added lane-aware road traffic metrics with per-segment vehicle capacity and congestion.','Truck speed now responds to local road congestion and road condition instead of only global traffic.','Road traffic state tracks active load, capacity and assigned lane for each road segment.']},
  {version:'1.0.14',date:'30 Sep 2026',items:['Road junction rendering now consumes the same canonical topology used by routing and editing.','3-way, 4-way and near-touching junction visuals now share one connectivity model.']},
  {version:'1.0.13',date:'30 Sep 2026',items:['Added canonical road topology metadata for junction, boundary and three-way/four-way connectivity.','Improved boundary road end visuals with edge lines and reflective posts.','Added regression coverage for junction topology.']},
  {version:'1.0.12',date:'30 Sep 2026',items:['Road editing now commits atomically with topology validation, junction preservation and route invalidation.','Improved 3D junction blending with curved flat turn connectors plus full-length bridge rails and supports.']},

  {version:'1.0.10',date:'30 Sep 2026',items:['Replaced the legacy Edit Roads interaction with a dedicated Edit Road action menu.','Added explicit Move endpoint and road deletion buttons.','Made road editing actions clearer and more touch-friendly on mobile.']},
  {version:'1.0.9',date:'30 Sep 2026',items:['Added four-way world-edge snapping for road drawing and endpoint dragging.','Added visible world boundary guides and clearer edge endpoint feedback.','Fixed road preview wiring so live road geometry renders while drawing.','Improved boundary-adjacent junction handling and added edge regression coverage.']},  {version:'1.0.8',date:'30 Sep 2026',items:['Fixed first road segment and endpoint editing when their index is 0.','Hardened mobile camera pointer handling and prevented default canvas touch gestures from leaking to the browser.','Cleared road editing state when switching modes, resetting the game or cancelling a pointer gesture.']},
  {version:'1.0.7',date:'30 Sep 2026',items:['Added Progressive Web App support with offline caching and install metadata.']},
  {version:'1.0.6',date:'30 Sep 2026',items:['Fixed building placement to report invalid locations instead of silently failing.','Fixed road endpoint editing and road deletion input handling.','Fixed road editing state cleanup when a pointer gesture is cancelled.']},
  {version:'1.0.5',date:'30 Sep 2026',items:['Fixed mobile camera gestures so one-finger panning, taps and two-finger pinch/pan do not fight each other.']},
  {version:'1.0.4',date:'30 Sep 2026',items:['Removed the legacy 2D renderer fallback and standardised rendering on the 3D renderer.']},
  {version:'1.0.3',date:'30 Sep 2026',items:['Added a visual, mobile-first build menu for roads, factories, shops and warehouses.','Added drag-to-map building placement with live valid/invalid feedback and prices.','Kept road construction on the existing road system while allowing a road card to start placement from the map.']},
  {version:'1.0',date:'30 Sep 2026',items:['Completed the first mobile-focused UI pass with touch-friendly controls and compact bottom sheets.','Improved road placement, snapping, endpoint editing and road cleanup.','Improved mobile build mode, toolbar layout and touch spacing.','Added clearer HUD progress, traffic and company information.','Hardened road editing and routing with automated regression coverage.']}
];

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
const canvas=document.querySelector('#game');let W=0,H=0;let s=load();let drag=null;let pointers=new Map();let pinch=null;let cameraGesture=null;let last=performance.now();let pinchCenter=null;let panelMode='none';let roadEditAction=null;
function resize(){W=innerWidth;H=innerHeight;resizeRenderer(W,H)}addEventListener('resize',resize);resize();
function load(){try{const d=JSON.parse(localStorage.getItem('miniFactoriesSaveV6'));const h=hydrate(d);if(h)return h}catch{}const n=freshState();seed(n);for(const b of n.buildings.filter(b=>b.kind==='shop'))newContract(n,b);return n}
function markWorldDirty(){s.renderVersion=(s.renderVersion||0)+1}
function save(){if(s.gameOver)return;try{localStorage.setItem('miniFactoriesSaveV6',JSON.stringify(serialise(s)))}catch(e){flash('Save failed — storage unavailable')}}
function roadResultMessage(result,path){if(result===true)return 'Road built';if(result==='cash'){const lengthEstimate=path.length>1?path.reduce((n,p,i)=>i?n+dist(path[i-1],p):0,0):0;const cost=Math.max(1,Math.ceil(lengthEstimate/180))*2;return 'Need £'+cost+' cash (you have £'+Math.floor(s.cash)+')'}if(result==='too-short')return 'Select two different points or buildings';if(result==='blocked')return 'Road blocked — move around the building';if(result==='duplicate')return 'Road already exists here';return 'Invalid road'}
function flash(text){const el=document.querySelector('#tip');el.textContent=text;clearTimeout(flash.timer);flash.timer=setTimeout(()=>el.textContent='Build roads between factories and shops.',1200)}
function roadPreviewTip(preview){if(!preview)return 'Build roads between factories and shops.';const state=preview.blocked?'Blocked — move around buildings':s.cash<preview.cost?'Need £'+preview.cost+' cash':'Ready';const snap=[];if(preview.start?.building)snap.push('start:building');else if(preview.start?.road)snap.push('start:road');else if(preview.edgeSnappedStart)snap.push('start:edge');else if(preview.gridSnappedStart)snap.push('start:grid');if(preview.end?.building)snap.push('end:building');else if(preview.end?.road)snap.push('end:road');else if(preview.edgeSnappedEnd)snap.push('end:edge');else if(preview.gridSnappedEnd)snap.push('end:grid');const snapText=snap.length?' • '+snap.join(' + '):'';return state+' • '+Math.round(preview.length)+'m • £'+preview.cost+snapText}
function reset(){closeBuildMenu();closeRoadEditor();localStorage.removeItem('miniFactoriesSaveV6');s=freshState();seed(s);s.renderVersion=1;for(const b of s.buildings.filter(b=>b.kind==='shop'))newContract(s,b);document.querySelector('#settingsMenu').style.display='none';document.querySelector('#gameOver').style.display='none';s.paused=false;hidePanel();sync();save();flash('New factory started')}
function renderChangeLog(){const el=document.querySelector('#changeLog');if(!el)return;el.innerHTML=CHANGELOG.map(v=>'<section class="changelog-version"><div class="changelog-head"><b>v'+v.version+'</b><span>'+v.date+'</span></div><ul>'+v.items.map(x=>'<li>'+x+'</li>').join('')+'</ul></section>').join('')}
renderChangeLog();bindBuildMenu();
function sync(){document.querySelector('#cash').textContent='£'+Math.floor(s.cash);document.querySelector('#orders').textContent=s.orders;document.querySelector('#companyLevel').textContent=s.companyLevel;const version=document.querySelector('#gameVersion');if(version)version.textContent='v'+GAME_VERSION;const levelProgress=document.querySelector('#levelProgress');if(levelProgress)levelProgress.style.width=Math.min(100,Math.max(0,(s.xp/Math.max(1,s.xpToNext))*100))+'%';const traffic=document.querySelector('#traffic');if(traffic)traffic.textContent=Math.round(Math.max(0,Math.min(100,(s.congestion||0)*100)))+'%';const g=s.goals[s.objective];document.querySelector('#objective').innerHTML=g?`<b>Goal ${s.objective+1}/6</b> • ${g.text} <span>${Math.min(g.target,Math.floor(g.progress(s)))}/${g.target}</span>`:'All objectives complete';const p=document.querySelector('#panel');if(panelMode==='building'&&s.selected&&p.style.display!=='none')showPanel(s.selected)}
function setMenuActive(id){document.querySelectorAll('.actions button').forEach(el=>el.classList.remove('active'));if(id)document.querySelector('#'+id)?.classList.add('active')}
function clearDynamicBuildButtons(){document.querySelectorAll('#panel button[id^="build"]').forEach(el=>el.style.display='none')}
function clearButtonActions(){for(let i=1;i<=4;i++){const el=document.querySelector('#u'+i);el.onclick=null}document.querySelector('#shop').onclick=null}
function showPanel(b){panelMode='building';setMenuActive(null);const p=document.querySelector('#panel');clearDynamicBuildButtons();clearButtonActions();p.style.display='block';p.classList.toggle('shop-panel',b.kind==='shop');p.classList.toggle('factory-panel',b.kind==='factory');p.classList.toggle('warehouse-panel',b.kind==='warehouse');document.querySelector('#objective').style.display='none';const t=TYPES.find(x=>x.name===b.type);document.querySelector('#name').textContent=b.type;document.querySelector('#panelHint').textContent=b.kind==='factory'?'Production and upgrades':b.kind==='warehouse'?'Storage and logistics':'Demand and deliveries';document.querySelector('#type').textContent=t?.role||(b.kind==='factory'?'Factory':'Shop');document.querySelector('#info').innerHTML=b.kind==='factory'?'<b>'+b.stock+'/'+b.max+'</b> stock • Lv '+b.level+'<br><small>'+(t?.desc||'Produces '+b.type+' for delivery.')+'</small>':b.kind==='warehouse'?'<b>'+Math.floor(b.storage||0)+'/'+b.max+'</b> storage • Lv '+b.level+'<br><small>Goods arriving from connected factories are stored here, then automatically sent to shops that need them.</small>':'<b>'+Math.ceil(b.demand)+'</b> demand • '+(b.contract?(b.contract.remaining+'/'+b.contract.qty+' on current job'):'waiting for a job')+'<br><small>'+(t?.desc||'Consumes '+b.need+' for local demand.')+'</small>';for(let i=1;i<=4;i++){const el=document.querySelector('#u'+i);el.onclick=null;const warehouse=b.kind==='warehouse';const factory=b.kind==='factory';el.style.display=(factory||(warehouse&&i<=2))?'block':'none';let price=0,label='',desc='',disabled=false;if(factory){price=i===1?120*b.level:i===2?180+(b.max-4)/2*70:i===3?220*(b.loading+1):300*(b.logistics+1);const labels=[['⚡ Faster machines','Increase production speed.'],['📦 Bigger storage','Increase maximum stock.'],['🚚 Loading bay','Faster dispatch and higher delivery value.'],['🧭 Logistics','Reduce congestion impact.']][i-1];label=labels[0];desc=labels[1];disabled=i===1?b.level>=3:i===2?b.max>=14:i===3?b.loading>=2:b.logistics>=2}else if(warehouse){price=i===1?(b.level===1?180:320):0;label=i===1?'📦 Expand storage':'🚚 Improve logistics';desc=i===1?'Increase warehouse capacity.':'Increase warehouse logistics efficiency.';disabled=i===1?b.level>=3:false}el.innerHTML=label+' <span>£'+Math.round(price)+'</span><small>'+desc+'</small>';el.disabled=disabled;el.onclick=()=>{if(!el.disabled&&upgrade(s,b,i)){save();sync();showPanel(b)}}}const shop=document.querySelector('#shop');shop.style.display=b.kind==='shop'?'inline-flex':'none';shop.onclick=null;if(b.kind==='shop'){shop.innerHTML='🏪 Upgrade shop <span>£'+(220*b.level)+'</span>';shop.disabled=b.level>=3;shop.onclick=()=>{if(!shop.disabled&&upgrade(s,b,1)){save();sync();showPanel(b)}}}}
let buildMenuOpen=false;let buildDrag=null;
function buildIcon(t){if(t.kind==='factory')return '🏭';if(t.kind==='shop')return '🏪';if(t.kind==='warehouse')return '📦';return '🛣️'}
function buildEntries(){return [{name:'Road',kind:'road',role:'Connect buildings',desc:'Drag onto the map to start a road.'},...TYPES]}
function buildPlacementReason(t,p){if(t.kind==='road')return null;return canPlaceBuildingAt(s,t,p.x,p.y)}
function renderBuildMenu(){const menu=document.querySelector('#buildMenu');if(!menu)return;const grid=document.querySelector('#buildCards');if(!grid)return;grid.innerHTML=buildEntries().map(t=>{const reason=t.kind==='road'?null:buildingUnlock(t,s);const cost=t.kind==='road'?'From £2':'£'+buildingCost(s,t);const locked=!!reason;const subtitle=reason||t.role||t.desc||'Build';return '<button class="build-card'+(locked?' locked':'')+'" data-build-type="'+t.name+'" '+(locked?'disabled':'')+'><span class="build-icon">'+buildIcon(t)+'</span><span class="build-copy"><b>'+t.name+'</b><small>'+subtitle+'</small></span><strong>'+cost+'</strong>'+(locked?'<span class="build-lock">🔒</span>':'')+'</button>'}).join('');menu.querySelector('.build-cash').textContent='£'+Math.floor(s.cash)}
function showBuild(){panelMode='build';s.selected=null;hidePanel();buildMenuOpen=true;setMenuActive('build');renderBuildMenu();document.querySelector('#buildMenu')?.classList.add('open');document.querySelector('#buildMenu')?.setAttribute('aria-hidden','false')}
function closeBuildMenu(){buildMenuOpen=false;buildDrag=null;document.querySelector('#buildMenu')?.classList.remove('open');document.querySelector('#buildMenu')?.setAttribute('aria-hidden','true');document.querySelector('#buildGhost')?.classList.remove('show');if(panelMode==='build')panelMode='none';if(s.mode==='build'){s.mode='select';s.buildMode=null}setMenuActive(null)}
function startBuild(t){if(t.kind==='road'){closeBuildMenu();s.buildMode=null;s.mode='road';setMenuActive('road');document.querySelector('#road').classList.add('active');document.querySelector('#erase').classList.remove('active');flash('Drag on the map to build a road');return}const reason=canBuild(s,t);if(reason){flash(reason);renderBuildMenu();return}closeBuildMenu();s.buildMode=t;s.mode='build';setMenuActive('build');document.querySelector('#road').classList.remove('active');document.querySelector('#erase').classList.remove('active');flash('Tap an empty area to place '+t.name)}
function buildCardForTarget(e){const card=e.target.closest('.build-card');if(!card)return null;const type=buildEntries().find(t=>t.name===card.dataset.buildType);return type&&type.kind!=='road'&&canBuild(s,type)?type:type}
function canvasDropPoint(clientX,clientY){const el=document.elementFromPoint(clientX,clientY);if(el!==canvas&&!canvas.contains(el))return null;return screenToWorld(clientX,clientY,W,H)}
function updateBuildGhost(clientX,clientY){const ghost=document.querySelector('#buildGhost');if(!ghost||!buildDrag)return;ghost.style.left=clientX+'px';ghost.style.top=clientY+'px';ghost.classList.add('show');const p=canvasDropPoint(clientX,clientY);const t=buildDrag.type;if(!p){ghost.classList.remove('valid');ghost.classList.add('invalid');ghost.querySelector('small').textContent='Drop on the map';return}if(t.kind==='road'){ghost.classList.remove('invalid');ghost.classList.add('valid');ghost.querySelector('small').textContent='Drop to start road';return}const reason=buildPlacementReason(t,p);ghost.classList.toggle('valid',!reason);ghost.classList.toggle('invalid',!!reason);ghost.querySelector('small').textContent=reason||'Release to build'}
function finishBuildDrag(e){if(!buildDrag)return;const d=buildDrag;buildDrag=null;const ghost=document.querySelector('#buildGhost');ghost?.classList.remove('show');if(!d.dragging){startBuild(d.type);return}const p=canvasDropPoint(e.clientX,e.clientY);if(!p){flash('Drop the building on the map');return}if(d.type.kind==='road'){const target=roadBuildingTarget(s,p)||roadTarget(s,p)||p;s.mode='road';s.buildMode=null;drag={start:target,current:target};closeBuildMenu();setMenuActive('road');document.querySelector('#road').classList.add('active');flash('Road start set — drag to the next point');return}const reason=buildPlacementReason(d.type,p);if(reason){flash(reason);renderBuildMenu();buildMenuOpen=true;document.querySelector('#buildMenu')?.classList.add('open');return}const built=placeBuilding(s,d.type,p.x,p.y);if(built){markWorldDirty();save();sync();renderBuildMenu();flash(d.type.name+' constructed')}}
function bindBuildMenu(){const menu=document.querySelector('#buildMenu');if(!menu)return;menu.addEventListener('pointerdown',e=>{const type=buildCardForTarget(e);if(!type)return;buildDrag={type,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,dragging:false};const ghost=document.querySelector('#buildGhost');if(ghost){ghost.querySelector('span').textContent=buildIcon(type);ghost.querySelector('b').textContent=type.name;ghost.querySelector('small').textContent=type.kind==='road'?'Drop to start road':'Drag onto the map';ghost.classList.remove('valid','invalid')}});menu.addEventListener('pointermove',e=>{if(!buildDrag||buildDrag.pointerId!==e.pointerId)return;const dx=e.clientX-buildDrag.startX,dy=e.clientY-buildDrag.startY;const moved=Math.hypot(dx,dy)>7;if(!moved)return;const vertical=Math.abs(dy)>Math.abs(dx)+4;if(!vertical)return;if(!buildDrag.dragging){buildDrag.dragging=true;try{menu.setPointerCapture(e.pointerId)}catch{}}e.preventDefault();updateBuildGhost(e.clientX,e.clientY)});menu.addEventListener('pointerup',e=>{if(!buildDrag||buildDrag.pointerId!==e.pointerId)return;finishBuildDrag(e)});menu.addEventListener('pointercancel',()=>{buildDrag=null;document.querySelector('#buildGhost')?.classList.remove('show')});document.querySelector('#buildMenuClose')?.addEventListener('click',closeBuildMenu)}
function showCompany(){panelMode='company';setMenuActive('company');s.selected=null;clearDynamicBuildButtons();clearButtonActions();const p=document.querySelector('#panel');p.classList.remove('shop-panel','factory-panel','warehouse-panel','research-panel','company-panel','build-panel');p.classList.add('company-panel');p.style.display='block';document.querySelector('#objective').style.display='none';document.querySelector('#name').textContent='Company';document.querySelector('#panelHint').textContent='Network overview';document.querySelector('#type').textContent='Expansion';const unlocked=s.buildings.length;const cap=10+(s.research?.industry||0)*2;document.querySelector('#info').innerHTML='<b>'+unlocked+'/'+cap+'</b> buildings • Level '+s.companyLevel+'<br><small>Research Industry to expand your maximum company size.</small>';document.querySelector('#shop').style.display='none';const items=[['u1','🏭 Production','Factories: '+s.buildings.filter(b=>b.kind==='factory').length],['u2','🏪 Retail','Shops: '+s.buildings.filter(b=>b.kind==='shop').length],['u3','🚚 Network','Roads: '+s.roads.length],['u4','📈 Performance','£'+Math.floor(s.deliveryIncome)+' delivery income • '+s.orders+' deliveries']];for(let i=1;i<=4;i++){const el=document.querySelector('#u'+i),item=items[i-1];el.style.display='block';el.disabled=true;el.innerHTML=item[1]+'<small>'+item[2]+'</small>'}}
function showResearch(){panelMode='research';setMenuActive('research');s.selected=null;clearDynamicBuildButtons();clearButtonActions();const p=document.querySelector('#panel');p.classList.remove('shop-panel','factory-panel','warehouse-panel','company-panel','build-panel');p.classList.add('research-panel');p.style.display='block';document.querySelector('#objective').style.display='none';document.querySelector('#name').textContent='Research';document.querySelector('#panelHint').textContent='Spend cash to unlock improvements';document.querySelector('#type').textContent='Company development';document.querySelector('#info').innerHTML='<b>Level '+s.companyLevel+'</b> • XP '+Math.floor(s.xp)+'/'+s.xpToNext;document.querySelector('#shop').style.display='none';const data=[['u1','automation','⚡ Automation','Faster factory production.'],['u2','logistics','🚚 Logistics','Higher delivery value.'],['u3','industry','🏭 Industry','Increase maximum city size.']];for(let i=0;i<4;i++)document.querySelector('#u'+(i+1)).style.display=i<3?'block':'none';for(const [id,key,label,desc] of data){const el=document.querySelector('#'+id),level=s.research[key]||0;el.innerHTML=label+' <span>£'+researchCost(s,key)+'</span><small>Lv '+level+'/3 • '+desc+'</small>';el.disabled=level>=3||s.cash<researchCost(s,key);el.onclick=()=>{if(research(s,key)){save();sync();showResearch()}}}}
function hidePanel(){const p=document.querySelector('#panel');if(buildMenuOpen)closeBuildMenu();setMenuActive(null);p.classList.remove('shop-panel','factory-panel','warehouse-panel','research-panel','company-panel','build-panel');panelMode='none';s.selected=null;s.buildMode=null;if(s.mode==='build')s.mode='select';document.querySelector('#panel').style.display='none';document.querySelector('#objective').style.display=''}
function closeRoadEditor(){const el=document.querySelector('#roadEditor');if(el){el.classList.remove('open');el.setAttribute('aria-hidden','true')}roadEditAction=null;s.mode='select';s.roadEditSelection=null;s.roadEditEndpoint=null;s.roadEditEndpointPreview=null;drag=null;setMenuActive(null);document.querySelector('#erase')?.classList.remove('active');document.querySelector('#tip').textContent='Build roads between factories and shops.'}
function openRoadEditor(){if(buildMenuOpen)closeBuildMenu();drag=null;s.mode='select';s.roadEditSelection=null;s.roadEditEndpoint=null;s.roadEditEndpointPreview=null;roadEditAction=null;const el=document.querySelector('#roadEditor');if(el){el.classList.add('open');el.setAttribute('aria-hidden','false')}setMenuActive(null)}
function startRoadEditAction(action){roadEditAction=action;const el=document.querySelector('#roadEditor');if(el){el.classList.remove('open');el.setAttribute('aria-hidden','true')}s.mode='erase';drag=null;s.roadEditSelection=null;s.roadEditEndpoint=null;s.roadEditEndpointPreview=null;setMenuActive('erase');document.querySelector('#erase')?.classList.add('active');const tips={move:'Drag a road endpoint',remove:'Tap any part of a road to delete it'};document.querySelector('#tip').textContent=tips[action]||'Edit road'}

function worldPos(e){const sp=screenPos(e);return screenToWorld(sp.x,sp.y,W,H)}
function panBy(dx,dy){panScreen(dx,dy,W,H)}
function screenPos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}function worldHitTolerance(screenPixels=22){const cx=W*.5,cy=H*.5,a=screenToWorld(cx,cy,W,H),b=screenToWorld(cx+screenPixels,cy,W,H);return Math.max(8,Math.min(70,Math.hypot(b.x-a.x,b.y-a.y)))}
function toggleMode(m){s.mode=s.mode===m?'select':m;setMenuActive(s.mode==='road'?'road':s.mode==='erase'?'erase':null);drag=null;s.roadEditHover=null;s.roadEditSelection=null;s.roadEditEndpoint=null;s.roadEditEndpointPreview=null;document.querySelector('#road').classList.toggle('active',s.mode==='road');document.querySelector('#erase').classList.toggle('active',s.mode==='erase');document.querySelector('#tip').textContent=s.mode==='erase'?'Drag a road endpoint • tap a road to delete it':'Build roads between factories and shops.'}
function setZoomAt(screen,z){s.camera.zoom=Math.max(.55,Math.min(2.4,z));zoomAtScreen(screen.x,screen.y,s.camera.zoom,W,H)}
canvas.addEventListener('pointerdown',e=>{e.preventDefault();try{canvas.setPointerCapture?.(e.pointerId)}catch{}const sp=screenPos(e);pointers.set(e.pointerId,sp);if(pointers.size===2){const [a,b]=[...pointers.values()];pinch={d:Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),z:s.camera.zoom};pinchCenter={x:(a.x+b.x)/2,y:(a.y+b.y)/2};cameraGesture={multi:true};drag=null;return}const p=worldPos(e);if(s.mode==='build'){if(!s.buildMode)return;const reason=canPlaceBuildingAt(s,s.buildMode,p.x,p.y);if(reason){flash(reason);return}const built=placeBuilding(s,s.buildMode,p.x,p.y);if(built){markWorldDirty();s.buildMode=null;s.mode='select';setMenuActive(null);save();sync();flash('Building constructed')}return}if(s.mode==='road'){const target=roadBuildingTarget(s,p)||roadTarget(s,p)||p;if(!drag)drag={start:target,current:target};return}if(s.mode==='erase'){if(roadEditAction==='move'){const endpoint=roadEndpointAtPoint(s,p,worldHitTolerance(30));if(endpoint){drag={road:endpoint.road,endpoint:endpoint.index};s.roadEditEndpoint={roadId:endpoint.roadId,index:endpoint.index,point:endpoint.point};s.roadEditEndpointPreview=roadEndpointPreview(s,endpoint.road,endpoint.index,p)}return}const hit=roadSegmentAtPoint(s,p,worldHitTolerance(26));if(hit){if(roadEditAction==='remove'){const result=editRoadSegment(s,p,'delete');s.roadEditSelection=null;if(result){markWorldDirty();save();sync();flash('Road deleted')}else flash('Could not delete road');return}}return}if(s.mode==='select'){cameraGesture={multi:false,startX:sp.x,startY:sp.y,lastX:sp.x,lastY:sp.y,moved:false,pointerId:e.pointerId};drag=null;return}const b=buildingAtPoint(s,p,worldHitTolerance(24));s.selected=b||null;if(b)showPanel(b);else hidePanel()});
canvas.addEventListener('pointermove',e=>{const sp=screenPos(e);pointers.set(e.pointerId,sp);if(pointers.size===2){const [a,b]=[...pointers.values()];if(!pinch){pinch={d:Math.max(1,Math.hypot(b.x-a.x,b.y-a.y)),z:s.camera.zoom};pinchCenter={x:(a.x+b.x)/2,y:(a.y+b.y)/2}}const d=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y));const c={x:(a.x+b.x)/2,y:(a.y+b.y)/2};setZoomAt(c,pinch.z*(d/pinch.d));panBy(c.x-pinchCenter.x,c.y-pinchCenter.y);pinchCenter=c;cameraGesture={multi:true};return}if(cameraGesture?.multi)return;const p=worldPos(e);if(s.mode==='road'&&drag){drag.current=roadBuildingTarget(s,p)||roadTarget(s,p)||p;const preview=roadPreview(s,drag.start,drag.current);setPreview(preview?.path,preview?.start,preview?.end,preview?.blocked);document.querySelector('#tip').textContent=roadPreviewTip(preview);return}if(s.mode==='erase'&&drag&&drag.endpoint!==undefined){s.roadEditEndpointPreview=roadEndpointPreview(s,drag.road,drag.endpoint,p);setPreview(null);return}if(s.mode==='erase'){s.roadEditHover=roadSegmentAtPoint(s,p,worldHitTolerance(22));setPreview(null);return}if(cameraGesture?.pointerId===e.pointerId&&s.mode==='select'){const dx=sp.x-cameraGesture.lastX,dy=sp.y-cameraGesture.lastY;if(Math.hypot(sp.x-cameraGesture.startX,sp.y-cameraGesture.startY)>7)cameraGesture.moved=true;if(cameraGesture.moved&&(dx||dy))panBy(dx,dy);cameraGesture.lastX=sp.x;cameraGesture.lastY=sp.y}});
canvas.addEventListener('pointerup',e=>{const wasMulti=!!cameraGesture?.multi||!!pinch;pointers.delete(e.pointerId);if(pointers.size<2)pinch=null;if(s.mode==='road'&&drag){const d=drag;drag=null;const target=roadBuildingTarget(s,d.current)||roadTarget(s,d.current)||d.current;const preview=roadPreview(s,d.start,target);const path=preview?.path||roadPathSafe(s,d.start,target);const meta={startBuilding:preview?.start?.building||d.start?.building,endBuilding:preview?.end?.building||target?.building};const result=addRoad(s,path,meta);setPreview(null);document.querySelector('#tip').textContent=roadResultMessage(result,path);if(result===true){markWorldDirty();save();sync()}}else if(s.mode==='erase'&&drag&&drag.endpoint!==undefined){const d=drag;drag=null;const p=worldPos(e);const result=editRoadEndpoint(s,d.road,d.endpoint,p);s.roadEditEndpoint=null;s.roadEditEndpointPreview=null;setPreview(null);if(result){markWorldDirty();save();sync();flash('Road endpoint moved')}else flash('Invalid road endpoint') }else if(s.mode==='erase'&&drag&&drag.segment!==undefined){drag=null}else if(s.mode==='select'&&cameraGesture&&!wasMulti&&cameraGesture.pointerId===e.pointerId){const g=cameraGesture;if(!g.moved){const p=worldPos(e);const b=buildingAtPoint(s,p,worldHitTolerance(24));s.selected=b||null;if(b)showPanel(b);else hidePanel()}}cameraGesture=null});
canvas.addEventListener('lostpointercapture',e=>{pointers.delete(e.pointerId);drag=null;pinch=null;cameraGesture=null;s.roadEditEndpoint=null;s.roadEditEndpointPreview=null;s.roadEditSelection=null;setPreview(null)});
canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);drag=null;pinch=null;cameraGesture=null;s.roadEditEndpoint=null;s.roadEditEndpointPreview=null;s.roadEditSelection=null;setPreview(null)});
canvas.addEventListener('wheel',e=>{e.preventDefault();const sp=screenPos(e);setZoomAt(sp,s.camera.zoom*(e.deltaY>0?.9:1.1))},{passive:false});
['gesturestart','gesturechange','gestureend'].forEach(type=>document.addEventListener(type,e=>e.preventDefault(),{passive:false}));
document.addEventListener('touchmove',e=>{if(e.touches.length>1)e.preventDefault()},{passive:false});
function roadPathSafe(s,a,b){try{const preview=roadPreview(s,a,b);return preview?.path||[a,b]}catch{return[a,b]}}
function tick(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(!s.paused&&!s.gameOver){updateEconomy(s,dt,flash);s.congestion=Math.min(1,(s.trucks.length/12)*.72+(s.roads.length/18)*.28);if(s.objective<s.goals.length&&s.goals[s.objective].done(s))s.objective=Math.min(s.goals.length,s.objective+1);if(s.cash<0)s.gameOver=true;save();sync()}render(s,W,H);if(!render.readySignalled){render.readySignalled=true;window.dispatchEvent(new Event('mini-factories-ready'));}requestAnimationFrame(tick)}
document.querySelector('#road').onclick=()=>toggleMode('road');
document.querySelector('#erase').onclick=()=>openRoadEditor();
document.querySelector('#roadEditorClose').onclick=closeRoadEditor;
document.querySelector('#roadEditorCancel').onclick=closeRoadEditor;
document.querySelector('#roadEditMove').onclick=()=>startRoadEditAction('move');
document.querySelector('#roadEditRemove').onclick=()=>startRoadEditAction('remove');
document.querySelector('#build').onclick=showBuild;
document.querySelector('#research').onclick=showResearch;
document.querySelector('#company').onclick=showCompany;
document.querySelector('#panelClose').onclick=hidePanel;
document.querySelector('#settings').onclick=()=>{s.paused=true;document.querySelector('#settingsMenu').style.display='flex'};
document.querySelector('#settingsClose').onclick=()=>{s.paused=false;document.querySelector('#settingsMenu').style.display='none'};
document.querySelector('#changeLogOpen').onclick=()=>{document.querySelector('#settingsMenu').style.display='none';document.querySelector('#changeLogPage').style.display='grid'};
document.querySelector('#changeLogClose').onclick=()=>{document.querySelector('#changeLogPage').style.display='none';document.querySelector('#settingsMenu').style.display='flex'};
document.querySelector('#newgame').onclick=()=>reset();document.querySelector('#again').onclick=()=>reset();document.querySelector('#cameraHome').onclick=()=>{resetCamera(W,H);s.renderVersion=(s.renderVersion||0)+1};requestAnimationFrame(tick);