import {freshState,hydrate,serialise,TYPES} from './state.js';
import {seed,spawn,nearestBuilding,nearestRoad,roadPath,addRoad,eraseRoad,dist} from './world.js';
import {updateEconomy,upgrade,newContract} from './economy.js';
import {render} from './render.js';

const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');let W=0,H=0,dpr=1;let s=load();let drag=null;let pointers=new Map();let pinch=null;let last=performance.now();
function resize(){dpr=devicePixelRatio||1;W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function load(){try{const d=JSON.parse(localStorage.getItem('miniFactoriesSaveV4'));const h=hydrate(d);if(h)return h}catch{}const n=freshState();seed(n);for(const b of n.buildings.filter(b=>b.kind==='shop'))newContract(n,b);return n}
function save(){if(s.gameOver)return;try{localStorage.setItem('miniFactoriesSaveV4',JSON.stringify(serialise(s)))}catch{}}
function flash(text){const el=document.querySelector('#tip');el.textContent=text;clearTimeout(flash.timer);flash.timer=setTimeout(()=>el.textContent='Build roads between factories and shops.',1200)}
function reset(){localStorage.removeItem('miniFactoriesSaveV4');s=freshState();seed(s);for(const b of s.buildings.filter(b=>b.kind==='shop'))newContract(s,b);sync();flash('New factory started')}
function sync(){document.querySelector('#cash').textContent='£'+Math.floor(s.cash);document.querySelector('#orders').textContent=s.orders;document.querySelector('#week').textContent=s.week;document.querySelector('#roads').textContent=s.roadBudget;const g=s.goals[s.objective];document.querySelector('#objective').innerHTML=g?`<b>Goal ${s.objective+1}/6</b> • ${g.text} <span>${Math.min(g.target,Math.floor(g.progress(s)))}/${g.target}</span>`:'All objectives complete';const p=document.querySelector('#panel');if(s.selected&&p.style.display!=='none')showPanel(s.selected);}
function showPanel(b){const p=document.querySelector('#panel');p.style.display='block';document.querySelector('#name').textContent=b.type;document.querySelector('#type').textContent=b.kind==='factory'?'Factory':'Shop';document.querySelector('#info').textContent=b.kind==='factory'?`${b.stock}/${b.max} stock • level ${b.level}`:`${Math.ceil(b.demand)} demand • ${b.contract?`${b.contract.remaining}/${b.contract.qty} contract`:'no contract'}`;for(let i=1;i<=4;i++){const el=document.querySelector('#u'+i);el.style.display=b.kind==='factory'?'block':'none';el.disabled=i===1?b.level>=3:i===2?b.max>=14:i===3?b.loading>=2:b.logistics>=2}document.querySelector('#shop').style.display=b.kind==='shop'?'block':'none';}
function hidePanel(){s.selected=null;document.querySelector('#panel').style.display='none'}
function worldPos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-s.camera.x)/s.camera.zoom+W/2,y:(e.clientY-r.top-s.camera.y)/s.camera.zoom+H/2}}
function panBy(dx,dy){s.camera.x+=dx;s.camera.y+=dy}
function screenPos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function toggleMode(m){s.mode=s.mode===m?'select':m;document.querySelector('#road').classList.toggle('active',s.mode==='road');document.querySelector('#erase').classList.toggle('active',s.mode==='erase')}
canvas.addEventListener('pointerdown',e=>{pointers.set(e.pointerId,screenPos(e));if(pointers.size===2){const a=[...pointers.values()][0],b=[...pointers.values()][1];pinch={d:Math.hypot(b.x-a.x,b.y-a.y),z:s.camera.zoom,cx:s.camera.x,cy:s.camera.y};drag=null;return}const p=worldPos(e);if(s.mode==='erase'){eraseRoad(s,p);save();return}if(s.mode==='select'){s.selected=nearestBuilding(s,p);if(s.selected)showPanel(s.selected);else hidePanel();if(!s.selected)drag={pan:true,last:screenPos(e)};return}const start=nearestRoad(s,p)||nearestBuilding(s,p)||p;drag={start,building:nearestBuilding(s,start),armed:false};canvas.setPointerCapture?.(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(pointers.has(e.pointerId))pointers.set(e.pointerId,screenPos(e));if(pinch&&pointers.size>=2){const a=[...pointers.values()][0],b=[...pointers.values()][1],d=Math.max(30,Math.hypot(b.x-a.x,b.y-a.y));s.camera.zoom=Math.max(.65,Math.min(1.8,pinch.z*d/pinch.d));return}if(drag?.pan&&s.mode==='select'){const q=screenPos(e);panBy(q.x-drag.last.x,q.y-drag.last.y);drag.last=q;return}if(!drag||s.mode!=='road')return;const p=worldPos(e);if(dist(drag.start,p)>8){drag.armed=true;drag.preview=roadPath(s,drag.start,p)}});
function finish(e){pointers.delete(e.pointerId);if(pinch&&pointers.size<2){pinch=null;drag=null;return}if(drag?.armed){const p=worldPos(e),path=roadPath(s,drag.start,p);if(addRoad(s,path)){flash('Road built');save()}else flash('Not enough road budget or cash')}drag=null}
canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);
for(const [id,fn] of [['road',()=>toggleMode('road')],['erase',()=>toggleMode('erase')],['pause',()=>{s.paused=!s.paused;document.querySelector('#pauseMenu').style.display=s.paused?'grid':'none'}],['resume',()=>{s.paused=false;document.querySelector('#pauseMenu').style.display='none'}],['newgame',reset],['again',reset]])document.querySelector('#'+id)?.addEventListener('click',fn);
for(let i=1;i<=4;i++)document.querySelector('#u'+i).addEventListener('click',()=>{if(s.selected&&upgrade(s,s.selected,i)){save();sync();showPanel(s.selected)}});document.querySelector('#shop').addEventListener('click',()=>{if(s.selected&&upgrade(s,s.selected,1)){save();sync();showPanel(s.selected)}});
function tick(dt){if(!s.paused&&!s.gameOver){updateEconomy(s,dt,flash);for(const p of s.particles)p.t+=dt;s.particles=s.particles.filter(p=>p.t<1);if(Math.random()<dt*.5)save()}sync();if(s.gameOver){document.querySelector('#gameOver').style.display='grid';document.querySelector('#score').textContent=`${s.orders} deliveries across ${s.week} weeks.`}}
function loop(now){const dt=Math.min(.05,(now-last)/1000);last=now;tick(dt);render(ctx,s,W,H);if(drag?.armed){const p=drag.preview;if(p){ctx.save();ctx.translate(s.camera.x,s.camera.y);ctx.scale(s.camera.zoom,s.camera.zoom);ctx.translate(-W/2,-H/2);ctx.strokeStyle='#8bd5ff99';ctx.lineWidth=6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++)ctx.lineTo(p[i].x,p[i].y);ctx.stroke();ctx.restore()}}requestAnimationFrame(loop)}sync();requestAnimationFrame(loop);