import {freshState,hydrate,serialise,TYPES} from './state.js';
import {seed,nearestBuilding,buildingAtPoint,roadBuildingTarget,nearestRoad,roadTarget,roadPreview,addRoad,editRoadSegment,roadSegmentAtPoint,roadEndpointAtPoint,roadEndpointPreview,editRoadEndpoint,dist,buildingCost,buildingUnlock,canBuild,canPlaceBuildingAt,buildingPlacementTarget,placeBuilding} from './world.js';
import {updateEconomy,upgrade,newContract,research,researchCost} from './economy.js';
import {render,setPreview,setBuildingPreview,resizeRenderer,controlCamera,screenToWorld,panScreen,zoomAtScreen,resetCamera} from './render.js';
import {createCommandHistory,AddRoadCommand,DeleteRoadCommand,MoveRoadEndpointCommand,PlaceBuildingCommand,executeCommand} from './commands.js';

const GAME_VERSION='1.3.1';
const CHANGELOG=[
  {version:'1.3.1',date:'1 Oct 2026',items:['Fixed the PWA update loop so the Refresh/Load Latest screen cannot trap the game.','Version and service-worker cache identifiers now stay in sync.']},
  {version:'1.3',date:'1 Oct 2026',items:['Refactored traffic around the directional lane graph instead of centreline-only routing.','Added smooth lane-change approaches, turn-specific lane offsets and curved junction connectors.','Added deterministic junction priority control with optional traffic-signal phases.','Truck routes now keep canonical centreline data separate from physical lane-position geometry.']},
  {version:'1.1',date:'1 Oct 2026',items:['Dedicated junction approach lanes and gradual road tapers.','Left, straight and right movement is selected before junctions and trucks position for the intended movement.','Truck queues now use physical following gaps and progressive braking.','Turning trucks follow smoother lane-specific arcs through junctions.','Junction road markings and directional arrows follow the new turning paths.','Factory → warehouse → shop logistics remains compatible with direct factory → shop deliveries.','Improved mobile road/building interaction and road editing.']},
  {version:'1.0',date:'1 Oct 2026',items:['Stable mobile-first release.','Road network, junctions, traffic, factories, warehouses and shops are now part of the core game.']}
];

if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{}));}
const canvas=document.querySelector('#game');let W=0,H=0;let s=load();let commands=createCommandHistory();let drag=null;let pointers=new Map();let pinch=null;let cameraGesture=null;let last=performance.now();let pinchCenter=null;let panelMode='none';let roadEditAction=null;let buildFilter='all';
function resize(){W=innerWidth;H=innerHeight;resizeRenderer(W,H)}addEventListener('resize',resize);resize();
function load(){try{const d=JSON.parse(localStorage.getItem('miniFactoriesSaveV6'));const h=hydrate(d);if(h)return h}catch{}const n=freshState();seed(n);for(const b of n.buildings.filter(b=>b.kind==='shop'))newContract(n,b);return n}
function markWorldDirty(){s.renderVersion=(s.renderVersion||0)+1}
function save(){if(s.gameOver)return;try{localStorage.setItem('miniFactoriesSaveV6',JSON.stringify(serialise(s)))}catch(e){flash('Save failed — storage unavailable')}}
function roadResultMessage(result,path){if(result===true)return 'Road built';if(result==='cash'){const lengthEstimate=path.length>1?path.reduce((n,p,i)=>i?n+dist(path[i-1],p):0,0):0;const cost=Math.max(1,Math.ceil(lengthEstimate/180))*2;return 'Need £'+cost+' cash (you have £'+Math.floor(s.cash)+')'}if(result==='too-short')return 'Select two different points or buildings';if(result==='blocked')return 'Road blocked — move around the building';if(result==='duplicate')return 'Road already exists here';return 'Invalid road'}
function flash(text){const el=document.querySelector('#tip');el.textContent=text;clearTimeout(flash.timer);flash.timer=setTimeout(()=>el.textContent='Build roads between factories and shops.',1200)}
function roadPreviewTip(preview){if(!preview)return 'Build roads between factories and shops.';const state=preview.blocked?'Blocked — move around buildings':s.cash<preview.cost?'Need £'+preview.cost+' cash':'Ready';const snap=[];if(preview.start?.building)snap.push('start:building');else if(preview.start?.road)snap.push('start:road');else if(preview.edgeSnappedStart)snap.push('start:edge');else if(preview.gridSnappedStart)snap.push('start:grid');if(preview.end?.building)snap.push('end:building');else if(preview.end?.road)snap.push('end:road');else if(preview.edgeSnappedEnd)snap.push('end:edge');else if(preview.gridSnappedEnd)snap.push('end:grid');const snapText=snap.length?' • '+snap.join(' + '):'';return state+' • '+Math.round(preview.length)+'m • £'+preview.cost+snapText}
function reset(){closeBuildMenu();closeRoadEditor();commands.clear();localStorage.removeItem('miniFactoriesSaveV6');s=freshState();seed(s);s.renderVersion=1;for(const b of s.buildings.filter(b=>b.kind==='shop'))newContract(s,b);document.querySelector('#settingsMenu').style.display='none';document.querySelector('#gameOver').style.display='none';s.paused=false;hidePanel();sync();save();flash('New factory started')}
function renderChangeLog(){const el=document.querySelector('#changeLog');if(!el)return;el.innerHTML=CHANGELOG.map(v=>'<section class="changelog-version"><div class="changelog-head"><b>v'+v.version+'</b><span>'+v.date+'</span></div><ul>'+v.items.map(x=>'<li>'+x+'</li>').join('')+'</ul></section>').join('')}
renderChangeLog();bindBuildMenu();
try{localStorage.setItem('miniFactoriesRuntimeVersion',GAME_VERSION)}catch{}
function sync(){document.querySelector('#cash').textContent='£'+Math.floor(s.cash);document.querySelector('#orders').textContent=s.orders;document.querySelector('#companyLevel').textContent=s.companyLevel;const version=document.querySelector('#gameVersion');if(version)version.textContent='v'+GAME_VERSION;const levelProgress=document.querySelector('#levelProgress');if(levelProgress)levelProgress.style.width=Math.min(100,Math.max(0,(s.xp/Math.max(1,s.xpToNext))*100))+'%';const traffic=document.querySelector('#traffic');if(traffic)traffic.textContent=Math.round(Math.max(0,Math.min(100,(s.congestion||0)*100)))+'%';const g=s.goals[s.objective];document.querySelector('#objective').innerHTML=g?`<b>Goal ${s.objective+1}/6</b> • ${g.text} <span>${Math.min(g.target,Math.floor(g.progress(s)))}/${g.target}</span>`:'All objectives complete';const p=document.querySelector('#panel');if(panelMode==='building'&&s.selected&&p.style.display!=='none')showPanel(s.selected)}
