import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/+esm';
import {riverY,isInsideWorldBounds,WORLD_BOUNDS,WORLD_MARGIN,WORLD_HALF_SIZE,roadTopology,buildingConnectionPoint,buildingHitbox,buildingDockPoints,roadAttachment} from './world.js';

let renderer=null,scene=null,camera3d=null,root=null,previewGroup=null,buildingPreviewGroup=null,roadEditGroup=null,roadEndpointGroup=null;
let target={x:0,z:0,yaw:0,pitch:.82,distance:620};
let desired={...target};
let home={x:0,z:0};
let cameraReady=false;
let viewport={width:1,height:1};
let previewKey='';
let buildingPreviewKey='';
let roadEditKey='';
let lastBuildingSelection=null;
const meshes=new Map();
const worldObjects=new Set();
const truckMeshes=new Map();
const routeMetrics=new WeakMap();
let ws=null;

function mat(color,roughness=.8,metalness=0){return new THREE.MeshStandardMaterial({color,roughness,metalness});}
function glassMat(color,opacity=.72){return new THREE.MeshStandardMaterial({color,roughness:.18,metalness:.04,transparent:true,opacity,depthWrite:false,side:THREE.DoubleSide});}
function box(w,h,d,color){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(color));}
function roadMat(color){return new THREE.MeshStandardMaterial({color,roughness:.9,metalness:0,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-2,polygonOffsetUnits:-2});}
function roadIntersection(a,b,c,d){const abx=b.x-a.x,aby=b.y-a.y,cdx=d.x-c.x,cdy=d.y-c.y,den=abx*cdy-aby*cdx;if(Math.abs(den)<1e-8)return null;const acx=c.x-a.x,acy=c.y-a.y,t=(acx*cdy-acy*cdx)/den,u=(acx*aby-acy*abx)/den;if(t<.0001||t>.9999||u<.0001||u>.9999)return null;return{x:a.x+abx*t,y:a.y+aby*t};}
const ROAD=Object.freeze({width:28,bridgeWidth:26,shoulderWidth:34,surfaceY:.68,shoulderY:.59,markingY:.80,curbY:.79,bridgeDeckY:.72,bridgeSurfaceY:.86,bridgeMarkingY:.98,railY:2.15});
const roadMaterials={asphalt:roadMat('#343a3c'),shoulder:roadMat('#697173'),curb:roadMat('#9aa09f'),center:mat('#e8e9e5',.72),edge:mat('#f1f1ec',.78),bridgeDeck:roadMat('#735334'),bridgeRail:mat('#b58a52'),bridgeSupport:mat('#5f4631')};
const sharedMaterials=new Set(Object.values(roadMaterials));
function addRoadBox(group,a,b,width,height,y,material){const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);if(len<1)return null;const mesh=new THREE.Mesh(new THREE.BoxGeometry(len,height,width),material);mesh.position.set((a.x+b.x)/2,y,(a.y+b.y)/2);mesh.rotation.y=-Math.atan2(dy,dx);group.add(mesh);return{mesh,len,dx,dy,angle:Math.atan2(dy,dx)};}
function samplePathByDistance(points,step=.8){const samples=[];if(!Array.isArray(points)||points.length<2)return samples;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],len=Math.hypot(b.x-a.x,b.y-a.y);if(len<.01)continue;const count=Math.max(1,Math.ceil(len/step));for(let j=0;j<count;j++){const t=j/count;samples.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});}}samples.push(points.at(-1));return samples;}
function addRibbonStrip(group,points,width,y,material){if(points.length<2)return;const mesh=new THREE.Mesh(ribbonGeometry(points,width,y,.08),material);mesh.renderOrder=3;group.add(mesh);}
function addRoadMarkings(group,points,width=ROAD.width,markingY=ROAD.markingY){if(!Array.isArray(points)||points.length<2)return;const samples=samplePathByDistance(points,.9);if(samples.length<2)return;const left=offsetPath(samples,width/2-1.6),right=offsetPath(samples,-(width/2-1.6));addRibbonStrip(group,left,.62,markingY,roadMaterials.edge);addRibbonStrip(group,right,.62,markingY,roadMaterials.edge);const dashLen=12,gap=18;let distance=10,run=0;for(let i=1;i<samples.length;i++){const a=samples[i-1],b=samples[i],seg=Math.hypot(b.x-a.x,b.y-a.y);if(seg<.01)continue;while(distance<run+seg-3){const start=distance,end=Math.min(distance+dashLen,run+seg-1),t0=(start-run)/seg,t1=(end-run)/seg;const dashStart={x:a.x+(b.x-a.x)*t0,y:a.y+(b.y-a.y)*t0},dashEnd={x:a.x+(b.x-a.x)*t1,y:a.y+(b.y-a.y)*t1};addRibbonStrip(group,[dashStart,dashEnd],1.02,markingY+.018,roadMaterials.center);distance+=dashLen+gap;}run+=seg;}}
function addRoadEndCap(group,p,radius,material,y){const cap=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,.11,32),material);cap.position.set(p.x,y,p.y);cap.receiveShadow=true;group.add(cap);}
function addRoadEndpointJoin(group,p,roadWidth){const join=new THREE.Mesh(new THREE.CylinderGeometry(roadWidth*.53,roadWidth*.53,.12,32),roadMaterials.asphalt);join.position.set(p.x,ROAD.surfaceY+.012,p.y);join.receiveShadow=true;group.add(join);const shoulder=new THREE.Mesh(new THREE.CylinderGeometry((roadWidth+6)*.53,(roadWidth+6)*.53,.08,32),roadMaterials.shoulder);shoulder.position.set(p.x,ROAD.shoulderY+.012,p.y);shoulder.receiveShadow=true;group.add(shoulder);}
function roundedRoadPoints(points){const clean=[];for(const p of points||[]){if(!Number.isFinite(p?.x)||!Number.isFinite(p?.y))continue;const last=clean.at(-1);if(last&&Math.hypot(last.x-p.x,last.y-p.y)<.5)continue;clean.push({x:p.x,y:p.y});}if(clean.length<3)return clean;const result=[clean[0]],radius=Math.min(30,Math.max(10,ROAD.width*1.35));for(let i=1;i<clean.length-1;i++){const prev=clean[i-1],cur=clean[i],next=clean[i+1],inLen=Math.hypot(cur.x-prev.x,cur.y-prev.y),outLen=Math.hypot(next.x-cur.x,next.y-cur.y);if(inLen<1||outLen<1){result.push(cur);continue;}const trim=Math.min(radius,inLen*.32,outLen*.32),inT={x:cur.x+(prev.x-cur.x)*(trim/inLen),y:cur.y+(prev.y-cur.y)*(trim/inLen)},outT={x:cur.x+(next.x-cur.x)*(trim/outLen),y:cur.y+(next.y-cur.y)*(trim/outLen)};result.push(inT);for(let s=1;s<=Math.max(3,Math.min(10,Math.ceil(trim/5)));s++){const t=s/Math.max(3,Math.min(10,Math.ceil(trim/5))),mt=1-t;result.push({x:mt*mt*inT.x+2*mt*t*cur.x+t*t*outT.x,y:mt*mt*inT.y+2*mt*t*cur.y+t*t*outT.y});}}result.push(clean.at(-1));return result;}
function ribbonGeometry(points,width,y,thickness=.12){const verts=[],indices=[];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b.x-a.x,dz=b.y-a.y,len=Math.hypot(dx,dz);if(!Number.isFinite(len)||len<.01)continue;const nx=-dz/len,nz=dx/len,half=width/2,base=verts.length/3;verts.push(a.x+nx*half,y-thickness/2,a.y+nz*half,a.x-nx*half,y-thickness/2,a.y-nz*half,b.x+nx*half,y-thickness/2,b.y+nz*half,b.x-nx*half,y-thickness/2,b.y-nz*half);indices.push(base,base+1,base+2,base+1,base+3,base+2);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(indices);g.computeVertexNormals();return g;}
function addRoadSurface(group,points,width,y,material){if(points.length<2)return;const mesh=new THREE.Mesh(ribbonGeometry(points,width,y,.14),material);mesh.receiveShadow=true;group.add(mesh);}
function offsetPath(points,offset){return points.map((p,i)=>{const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)];let tx=next.x-prev.x,tz=next.y-prev.y,len=Math.hypot(tx,tz)||1;tx/=len;tz/=len;return{x:p.x-tz*offset,y:p.y+tx*offset};});}
function addRoadCurbs(group,points,width){for(const side of[-1,1]){const curbPoints=offsetPath(points,side*(width/2+.45));const mesh=new THREE.Mesh(ribbonGeometry(curbPoints,1.05,ROAD.curbY,.20),roadMaterials.curb);mesh.castShadow=true;mesh.receiveShadow=true;group.add(mesh);}}
function addFlatCurve(group,start,control,end,width,y,material,steps=8){const points=[];for(let i=0;i<=steps;i++){const t=i/steps,mt=1-t;points.push({x:mt*mt*start.x+2*mt*t*control.x+t*t*end.x,y:mt*mt*start.y+2*mt*t*control.y+t*t*end.y});}addRoadSurface(group,points,width,y,material);}
function addRoadRails(group,points,width){const postGeo=new THREE.CylinderGeometry(.42,.52,2.25,8);for(const side of[-1,1]){for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b.x-a.x,dz=b.y-a.y,len=Math.hypot(dx,dz);if(len<1)continue;const angle=Math.atan2(dz,dx),nx=-Math.sin(angle),nz=Math.cos(angle);const rail=new THREE.Mesh(new THREE.BoxGeometry(len+.7,.62,.48),roadMaterials.bridgeRail);rail.position.set((a.x+b.x)/2+nx*side*(width/2+.9),ROAD.railY,(a.y+b.y)/2+nz*side*(width/2+.9));rail.rotation.y=-angle;rail.castShadow=true;group.add(rail);const count=Math.max(1,Math.floor(len/22));for(let p=0;p<=count;p++){const t=p/count,x=a.x+dx*t+nx*side*(width/2+.9),z=a.y+dz*t+nz*side*(width/2+.9);const post=new THREE.Mesh(postGeo,roadMaterials.bridgeRail);post.position.set(x,ROAD.railY-.72,z);post.castShadow=true;group.add(post);}}}}
function addBridgeSupports(group,points){const total=points.slice(1).reduce((n,p,i)=>n+Math.hypot(p.x-points[i].x,p.y-points[i].y),0);if(total<55)return;const pierGeo=new THREE.CylinderGeometry(2.4,3.1,ROAD.bridgeDeckY+10,8),capGeo=new THREE.BoxGeometry(10,1.4,3.6);const count=Math.max(1,Math.floor(total/95));for(let s=1;s<=count;s++){const target=total*s/(count+1);let run=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],seg=Math.hypot(b.x-a.x,b.y-a.y);if(run+seg<target){run+=seg;continue;}const t=(target-run)/Math.max(1,seg),x=a.x+(b.x-a.x)*t,z=a.y+(b.y-a.y)*t;const pier=new THREE.Mesh(pierGeo,roadMaterials.bridgeSupport);pier.position.set(x,-4.3,z);pier.castShadow=true;group.add(pier);const cap=new THREE.Mesh(capGeo,roadMaterials.bridgeSupport);cap.position.set(x,ROAD.bridgeDeckY-.4,z);cap.castShadow=true;group.add(cap);break;}}for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],dx=b.x-a.x,dz=b.y-a.y,len=Math.hypot(dx,dz);if(len<12)continue;const angle=Math.atan2(dz,dx);for(const side of[-1,1]){const girder=new THREE.Mesh(new THREE.BoxGeometry(len,2.2,1.6),roadMaterials.bridgeSupport);girder.position.set((a.x+b.x)/2,ROAD.bridgeDeckY-2.0,(a.y+b.y)/2+side*(ROAD.bridgeWidth*.34));girder.rotation.y=-angle;girder.castShadow=true;group.add(girder);}}}
function addBoundaryRoadEnd(group,p,width,y){const minX=WORLD_BOUNDS.minX+WORLD_MARGIN,maxX=WORLD_BOUNDS.maxX-WORLD_MARGIN,minY=WORLD_BOUNDS.minY+WORLD_MARGIN,maxY=WORLD_BOUNDS.maxY-WORLD_MARGIN,nearX=Math.abs(p.x-minX)<2||Math.abs(p.x-maxX)<2,nearY=Math.abs(p.y-minY)<2||Math.abs(p.y-maxY)<2;if(!nearX&&!nearY)return;const line=new THREE.Mesh(new THREE.BoxGeometry(width+.8,.12,1.2),roadMaterials.edge);line.position.set(p.x,y+.06,p.y);line.rotation.y=nearY?0:Math.PI/2;group.add(line);for(const side of[-1,1]){const post=new THREE.Mesh(new THREE.BoxGeometry(1.4,7,1.4),roadMaterials.edge);if(nearY)post.position.set(p.x+side*Math.min(7,width*.35),y+3.5,p.y);else post.position.set(p.x,y+3.5,p.y+side*Math.min(7,width*.35));group.add(post);}}
function buildingForRoadEndpoint(s,p){let best=null,bd=9;for(const b of s.buildings||[]){const q=buildingConnectionPoint(b,p,0),d=Math.hypot(q.x-p.x,q.y-p.y);if(d<bd){bd=d;best={building:b,facade:q};}}return best;}
function addBuildingAccessApron(group,building,roadPoint,facade,bridge){if(!building||bridge)return;const dx=roadPoint.x-facade.x,dy=roadPoint.y-facade.y,len=Math.hypot(dx,dy);if(len<1)return;const ux=dx/len,uy=dy/len,apronLength=Math.max(10,Math.min(22,len+7));const outer={x:facade.x+ux*apronLength,y:facade.y+uy*apronLength},shoulderWidth=ROAD.shoulderWidth+2,roadWidth=ROAD.width+3,points=[facade,{x:facade.x+ux*apronLength*.45,y:facade.y+uy*apronLength*.45},outer];addRoadSurface(group,points,shoulderWidth,ROAD.shoulderY+.018,roadMaterials.shoulder);addRoadSurface(group,points,roadWidth,ROAD.surfaceY+.018,roadMaterials.asphalt);addRoadCurbs(group,points,roadWidth);}
function splitRoadByWater(points){
  if(!Array.isArray(points)||points.length<2)return [];
  const bankHalfWidth=41;
  const runs=[];
  let current=null;
  const pushPoint=(kind,p)=>{
    if(!current||current.kind!==kind){if(current&&current.points.length>1)runs.push(current);current={kind,points:[p]};return;}
    const last=current.points.at(-1);if(!last||Math.hypot(last.x-p.x,last.y-p.y)>.05)current.points.push(p);
  };
  const classify=p=>Math.abs(p.y-riverY(p.x))<=bankHalfWidth?'water':'land';
  const refine=(a,b,fa,fb)=>{let lo=0,hi=1;for(let i=0;i<9;i++){const mid=(lo+hi)/2,t=mid,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t,f=Math.abs(y-riverY(x))-bankHalfWidth;if((fa<=0&&f<=0)||(fa>=0&&f>=0)){lo=mid;}else{hi=mid;}}const t=(lo+hi)/2;return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t};};
  for(let i=1;i<points.length;i++){
    const a=points[i-1],b=points[i],len=Math.hypot(b.x-a.x,b.y-a.y),steps=Math.max(2,Math.ceil(len/6));
    let prev={x:a.x,y:a.y},prevF=Math.abs(prev.y-riverY(prev.x))-bankHalfWidth;
    pushPoint(classify(prev),prev);
    for(let s=1;s<=steps;s++){
      const t=s/steps,p={x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t},f=Math.abs(p.y-riverY(p.x))-bankHalfWidth;
      if((prevF<0&&f>0)||(prevF>0&&f<0)){const edge=refine(prev,p,prevF,f),before=classify({x:edge.x+(prev.x-edge.x)*.001,y:edge.y+(prev.y-edge.y)*.001});pushPoint(before,edge);pushPoint(classify(p),edge);}
      pushPoint(classify(p),p);prev=p;prevF=f;
    }
  }
  if(current&&current.points.length>1)runs.push(current);
  return runs;
}
function makeRoad(points,bridge,s=null){
  if(!Array.isArray(points)||points.length<2)return new THREE.Group();
  const group=new THREE.Group(),clean=roundedRoadPoints(points);
  if(clean.length<2)return group;
  const runs=bridge?splitRoadByWater(clean):[{kind:'land',points:clean}];
  for(const run of runs){
    if(run.points.length<2)continue;
    if(run.kind==='water'){
      addRoadSurface(group,run.points,ROAD.bridgeWidth+2,ROAD.bridgeDeckY,roadMaterials.bridgeDeck);
      addRoadSurface(group,run.points,ROAD.bridgeWidth,ROAD.bridgeSurfaceY,roadMaterials.asphalt);
      addRoadMarkings(group,run.points,ROAD.bridgeWidth,ROAD.bridgeMarkingY);
      addRoadRails(group,run.points,ROAD.bridgeWidth);
      addBridgeSupports(group,run.points);
    }else{
      addRoadSurface(group,run.points,ROAD.shoulderWidth,ROAD.shoulderY,roadMaterials.shoulder);
      addRoadSurface(group,run.points,ROAD.width,ROAD.surfaceY,roadMaterials.asphalt);
      addRoadMarkings(group,run.points,ROAD.width);
      addRoadCurbs(group,run.points,ROAD.width);
    }
  }
  if(s)for(const p of[clean[0],clean.at(-1)]){const connection=buildingForRoadEndpoint(s,p);if(connection)addBuildingAccessApron(group,connection.building,p,connection.facade,false);}
  addRoadEndCap(group,clean[0],ROAD.shoulderWidth/2,roadMaterials.shoulder,ROAD.shoulderY);
  addRoadEndCap(group,clean.at(-1),ROAD.shoulderWidth/2,roadMaterials.shoulder,ROAD.shoulderY);
  if(!bridge){addRoadEndpointJoin(group,clean[0],ROAD.width);addRoadEndpointJoin(group,clean.at(-1),ROAD.width);addBoundaryRoadEnd(group,clean[0],ROAD.width,ROAD.shoulderY);addBoundaryRoadEnd(group,clean.at(-1),ROAD.width,ROAD.shoulderY);}
  return group;
}
function roadDirection(a,b){const dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);return len?{x:dx/len,y:dy/len}:null;}
function addLaneAwareJunction(group,center,connections){if(connections.length<2)return;const radius=ROAD.width*.66+Math.min(9,connections.length*1.6),apronRadius=radius+ROAD.shoulderWidth*.18;const apron=new THREE.Mesh(new THREE.CylinderGeometry(apronRadius,apronRadius,.10,64),roadMaterials.shoulder);apron.position.set(center.x,ROAD.shoulderY-.015,center.y);apron.receiveShadow=true;group.add(apron);const asphalt=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,.16,64),roadMaterials.asphalt);asphalt.position.set(center.x,ROAD.surfaceY-.015,center.y);asphalt.receiveShadow=true;group.add(asphalt);const sorted=[...connections].sort((a,b)=>Math.atan2(a.outer.y-center.y,a.outer.x-center.x)-Math.atan2(b.outer.y-center.y,b.outer.x-center.x));const innerRadius=radius*.58;for(let i=0;i<sorted.length;i++){const a=sorted[i],b=sorted[(i+1)%sorted.length],aa=Math.atan2(a.outer.y-center.y,a.outer.x-center.x),ab=Math.atan2(b.outer.y-center.y,b.outer.x-center.x);let delta=ab-aa;if(delta<0)delta+=Math.PI*2;if(delta<.25||delta>Math.PI*1.5)continue;const mid=aa+delta/2,sweep=Math.min(delta-.18,Math.PI*.72),start=mid-sweep/2,end=mid+sweep/2,curve=[];for(let s=0;s<=14;s++){const t=s/14,ang=start+(end-start)*t;curve.push({x:center.x+Math.cos(ang)*innerRadius,y:center.y+Math.sin(ang)*innerRadius});}addRibbonStrip(group,curve,ROAD.width*.9,ROAD.surfaceY+.09,roadMaterials.asphalt);}}
function makeRoadJunctions(roads){const group=new THREE.Group();const network=roadTopology({roads:(roads||[]).filter(road=>!road?.bridge)});for(const node of network.nodes){const links=network.adjacency.get(node)||[];if(links.length<3)continue;const connections=[];for(const link of links){const dx=link.node.x-node.x,dy=link.node.y-node.y,len=Math.hypot(dx,dy)||1;connections.push({inner:{x:node.x,y:node.y},outer:{x:node.x+dx/len*20,y:node.y+dy/len*20}});}const unique=[];for(const connection of connections)if(!unique.some(existing=>Math.abs(existing.outer.x-connection.outer.x)<8&&Math.abs(existing.outer.y-connection.outer.y)<8))unique.push(connection);if(unique.length>=3){const active=unique.slice(0,4),center={x:node.x,y:node.y},radius=ROAD.width*.66+Math.min(9,active.length*1.6);addLaneAwareJunction(group,center,active);addJunctionControlLines(group,center,active,radius);}}return group;}
function addJunctionControlLines(group,center,connections,radius){for(const connection of connections){const d=roadDirection(connection.inner,connection.outer);if(!d)continue;const travel={x:-d.x,y:-d.y},left={x:-travel.y,y:travel.x};const distance=radius+9,centerOffset=7,p={x:center.x+d.x*distance+left.x*centerOffset,y:center.y+d.y*distance+left.y*centerOffset},a={x:p.x-travel.x*(ROAD.width*.56),y:p.y-travel.y*(ROAD.width*.56)},b={x:p.x+travel.x*(ROAD.width*.56),y:p.y+travel.y*(ROAD.width*.56)};addRibbonStrip(group,[a,b],.92,ROAD.markingY+.035,roadMaterials.edge);}}
function disposeMaterial(material){if(Array.isArray(material)){material.forEach(disposeMaterial);return;}if(!material||sharedMaterials.has(material))return;material.dispose?.();}
function disposeObject(g){g.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)disposeMaterial(o.material);});}
function clearDynamic(){for(const g of worldObjects){scene.remove(g);disposeObject(g);}worldObjects.clear();meshes.clear();for(const g of truckMeshes.values()){scene.remove(g);disposeObject(g);}truckMeshes.clear();}
function createTerrain(){const g=new THREE.Group();g.name='terrain';const geometry=new THREE.PlaneGeometry(2600,2600,1,1);const material=new THREE.MeshStandardMaterial({color:'#789661',roughness:1,metalness:0});const mesh=new THREE.Mesh(geometry,material);mesh.rotation.x=-Math.PI/2;mesh.position.y=.08;mesh.receiveShadow=false;g.add(mesh);return g;}
function init(canvas){if(renderer)return;const mobile=canvas.clientWidth<=700;renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance',stencil:false});renderer.setPixelRatio(Math.min(globalThis.devicePixelRatio||1,mobile?1.5:2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=!mobile;scene=new THREE.Scene();scene.background=new THREE.Color('#b9c7b0');scene.fog=new THREE.Fog('#b9c7b0',900,2600);root=new THREE.Group();scene.add(root);previewGroup=new THREE.Group();scene.add(previewGroup);buildingPreviewGroup=new THREE.Group();scene.add(buildingPreviewGroup);roadEditGroup=new THREE.Group();scene.add(roadEditGroup);roadEndpointGroup=new THREE.Group();scene.add(roadEndpointGroup);scene.add(new THREE.HemisphereLight('#f8fbff','#58645d',1.55));const sun=new THREE.DirectionalLight('#fff8e8',1.75);sun.position.set(-260,420,220);sun.castShadow=true;sun.shadow.bias=-0.00025;sun.shadow.normalBias=0.22;sun.shadow.mapSize.set(mobile?1024:2048,mobile?1024:2048);sun.shadow.camera.near=10;sun.shadow.camera.far=1400;sun.shadow.camera.left=-520;sun.shadow.camera.right=520;sun.shadow.camera.top=520;sun.shadow.camera.bottom=-520;scene.add(sun);const fill=new THREE.DirectionalLight('#c8dcff',0.6);fill.position.set(180,220,-260);scene.add(fill);const ground=box(2600,2,2600,'#70845f');ground.position.y=-8;ground.receiveShadow=false;scene.add(ground);scene.add(createTerrain());const river=new THREE.Group(),riverWidth=82,riverStart=-1300,riverStep=44;for(let x=riverStart;x<=1300;x+=riverStep){const x2=Math.min(1300,x+riverStep+8),mid=(x+x2)/2,dy=riverY(x2)-riverY(x),angle=Math.atan2(dy,x2-x),segment=box(Math.hypot(x2-x,dy)+10,.7,riverWidth,'#6f98a3');segment.position.set(mid,.1,(riverY(x)+riverY(x2))/2);segment.rotation.y=-angle;river.add(segment);}scene.add(river);addEnvironment();resize(canvas.clientWidth||innerWidth,canvas.clientHeight||innerHeight);}
function resize(w,h){if(!renderer)return;viewport.width=Math.max(1,w);viewport.height=Math.max(1,h);renderer.setSize(viewport.width,viewport.height,false);if(camera3d){camera3d.aspect=viewport.width/viewport.height;camera3d.updateProjectionMatrix();}}