import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/+esm?v=4';
import {riverY,WORLD_BOUNDS,WORLD_MARGIN,buildingDockPoints,buildingRoadEntrance} from './world.js';
let renderer=null,scene=null,camera=null,root=null,previewGroup=null,buildingPreviewGroup=null;
let viewport={width:1,height:1};let target={x:0,z:0,yaw:0,pitch:.82,distance:620};let desired={...target};let worldKey='';
const buildingMeshes=new Map(),truckMeshes=new Map(),shared=new Set();
function material(color,roughness=.82,metalness=0){const m=new THREE.MeshStandardMaterial({color,roughness,metalness});shared.add(m);return m;}
function glass(color='#284b52'){return material(color,.18,.12);}
function part(g,geometry,mat,x,y,z,ry=0,cast=true){const m=new THREE.Mesh(geometry,mat);m.position.set(x,y,z);m.rotation.y=ry;m.castShadow=cast;m.receiveShadow=true;g.add(m);return m;}
function box(g,w,h,d,mat,x,y,z,ry=0,cast=true){return part(g,new THREE.BoxGeometry(w,h,d),mat,x,y,z,ry,cast);}
function cyl(g,r,h,mat,x,y,z,segments=16){return part(g,new THREE.CylinderGeometry(r,r,h,segments),mat,x,y,z,0,true);}
function addWindows(g,w,d,y,glassMat,frameMat,front=true){const span=front?w:d,count=Math.max(4,Math.floor(span/16));for(let i=0;i<count;i++){const t=(i+.5)/count;if(front){const x=-w/2+t*w;box(g,7,5,.28,glassMat,x,y,d/2+.16);box(g,.45,5.5,.42,frameMat,x-3.7,y,d/2+.05);box(g,.45,5.5,.42,frameMat,x+3.7,y,d/2+.05);}else{const z=-d/2+t*d;box(g,.28,5,7,glassMat,w/2+.16,y,z);box(g,.42,5.5,.45,frameMat,w/2+.05,y,z-3.7);box(g,.42,5.5,.45,frameMat,w/2+.05,y,z+3.7);}}}
function foundation(g,w,d,concrete){box(g,w+8,.7,d+8,concrete,0,.35,0,false);box(g,w+3,.8,d+3,material('#555c5a',.96),0,1,0,false);}
function loadingDoor(g,x,z,w,h,front,metal,dark){box(g,w+3,h+3,.55,metal,x,h/2+2,z);box(g,w,h,dark,x,h/2+2,z-front*.35,false);for(const side of[-1,1])box(g,1.2,h+.5,.8,metal,x+side*(w/2+1),h/2+2,z-front*.2);}
function dockStrip(g,x,z,w,front,mat){box(g,w,1.1,7,mat,x,1,z+front*2,false);for(let i=0;i<Math.max(3,Math.floor(w/12));i++){const px=x-w/2+6+i*12;box(g,.5,1.25,6,material('#aeb4ae',.72),px,1.65,z+front*2,false);}}
function gate(g,z,width,metal){const dark=material('#303635',.98);for(const x of[-width/2,width/2]){box(g,2.2,8,1.4,metal,x,4,z);box(g,1,5,.5,dark,x,4,z-.8);}box(g,width+2,.65,1.1,metal,0,8,z);}
function fence(g,x1,z1,x2,z2,metal){const dx=x2-x1,dz=z2-z1,len=Math.hypot(dx,dz),a=Math.atan2(dz,dx);if(len<1)return;box(g,len,.35,.7,metal,(x1+x2)/2,2.2,(z1+z2)/2,a,false);for(let d=0;d<=len;d+=14)cyl(g,.35,4,metal,x1+Math.cos(a)*d,2.1,z1+Math.sin(a)*d,8);}
function yard(g,b,kind,metal){const dock=buildingDockPoints(b)[0],entrance=buildingRoadEntrance(b);if(!dock||!entrance)return;const dockZ=dock.y-b.y,gateZ=entrance.y-b.y,dir=Math.sign(gateZ-dockZ)||1,width=kind==='warehouse'?286:kind==='factory'?244:176,depth=kind==='warehouse'?112:kind==='factory'?94:78,asphalt=material('#515957',.98),paint=material('#d6d9d4',.68);const center=(gateZ+dockZ)/2;box(g,width,.18,depth,asphalt,0,.12,center,0,false);box(g,width+8,.08,depth+8,material('#737a76',.98),0,.04,center,0,false);const laneWidth=kind==='warehouse'?34:30;box(g,laneWidth,.09,Math.abs(gateZ-dockZ)+20,material('#454c4a',.98),0,.23,center,0,false);for(const x of[-width*.33,width*.33])box(g,1.1,.1,depth-10,paint,x,.3,center,0,false);const radius=kind==='warehouse'?44:kind==='factory'?38:31;const pad=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,.22,48),asphalt);pad.position.set(0,.24,gateZ);pad.receiveShadow=true;g.add(pad);for(const side of[-1,1])fence(g,side*width/2,dockZ,side*width/2,gateZ,metal);gate(g,gateZ,kind==='warehouse'?46:kind==='factory'?42:34,metal);for(const x of[-width*.30,width*.30]){box(g,16,.25,10,material('#68716d',.92),x,.28,dockZ+dir*12,0,false);box(g,12,3,7,material('#b3b7b2',.9),x,2,dockZ+dir*12);cyl(g,1.8,2.4,metal,x+5,1.25,dockZ+dir*12,12);}box(g,width*.5,.12,3,paint,0,.3,gateZ-dir*12,0,false);}
function factoryModel(b){const g=new THREE.Group(),w=166,d=118,h=46;const body=material('#727a78',.9),dark=material('#343b3a',.97),metal=material('#59615f',.8,.18),accent=material(b.color||'#789a86',.55,.16),gl=glass(),roofMat=material('#424947',.96);foundation(g,w,d,metal);box(g,w,h,d,body,0,h/2+2,0);box(g,w*.9,3,d+.8,accent,0,8,d/2+.4);addWindows(g,w,d,20,gl,dark,true);addWindows(g,w,d,20,gl,dark,false);loadingDoor(g,0,d/2+.5,34,20,1,metal,dark);loadingDoor(g,-w*.32,d/2+.5,22,15,1,metal,dark);loadingDoor(g,w*.32,-d/2-.5,20,14,-1,metal,dark);dockStrip(g,0,d/2+.5,34,1,metal);box(g,w+8,3,d+8,roofMat,0,h+3,0);box(g,w*.34,8,d*.58,dark,-w*.29,h+7,0);box(g,w*.22,12,d*.44,metal,w*.31,h+9,0);for(const x of[-w*.34,w*.34]){cyl(g,5.2,28,dark,x,h+16,0,18);cyl(g,5.6,1.5,metal,x,h+30,0,18);box(g,10,3,5,metal,x,h+5,0);}for(const x of[-w*.22,0,w*.22]){box(g,18,3.5,10,dark,x,h+7,-d*.05);box(g,13,1.2,7,metal,x,h+9,-d*.05);}yard(g,b,'factory',metal);box(g,28,.18,38,material('#414846',.98),-w*.36,.2,d/2+42,0,false);return g;}
function warehouseModel(b){const g=new THREE.Group(),w=194,d=132,h=39;const body=material('#858d89',.93),dark=material('#3b4240',.98),metal=material('#626a66',.82,.12),accent=material(b.color||'#b7a25f',.56,.14),gl=glass(),roofMat=material('#4c5350',.96);foundation(g,w,d,metal);box(g,w,h,d,body,0,h/2+2,0);box(g,w*.88,3,d+.8,accent,0,7,d/2+.4);addWindows(g,w,d,18,gl,dark,true);loadingDoor(g,-w*.33,d/2+.5,24,16,1,metal,dark);loadingDoor(g,0,d/2+.5,38,20,1,metal,dark);loadingDoor(g,w*.33,d/2+.5,24,16,1,metal,dark);dockStrip(g,0,d/2+.5,38,1,metal);box(g,w+8,3,d+8,roofMat,0,h+3,0);box(g,w*.58,9,d*.74,body,-w*.05,h+7,0);box(g,w*.18,15,d*.5,dark,w*.35,h+10,0);for(const x of[-w*.3,-w*.05,w*.2]){box(g,15,3.2,9,dark,x,h+9,0);box(g,11,1.2,6,metal,x,h+10.8,0);}yard(g,b,'warehouse',metal);return g;}
function shopModel(b){const g=new THREE.Group(),w=158,d=106,h=32;const body=material('#777f7b',.88),dark=material('#2f3735',.97),metal=material('#68716d',.78,.14),accent=material(b.color||'#c39a45',.5,.16),gl=glass('#315c63'),roofMat=material('#454c49',.94);foundation(g,w,d,metal);box(g,w*.72,h+8,d*.72,body,-w*.08,(h+8)/2+2,-d*.02);box(g,w*.3,h-3,d*.5,dark,w*.34,(h-3)/2+2,.05);box(g,w*.74,5,d*.2,accent,-w*.08,h+6,-d*.18);addWindows(g,w*.72,d*.72,17,gl,dark,true);loadingDoor(g,w*.34,d/2+.5,22,16,1,metal,dark);dockStrip(g,w*.34,d/2+.5,22,1,metal);box(g,w*.46,2.5,d*.34,metal,w*.08,h+5,.02);for(const x of[-w*.25,-w*.08,w*.09,w*.26])box(g,7,5,.3,gl,x,13,d*.36);box(g,w*.52,2.8,8,metal,-w*.1,22,d/2+3);for(const x of[-w*.32,w*.18])cyl(g,1.8,12,metal,x,h+10,0,14);yard(g,b,'shop',metal);return g;}
function makeBuilding(b){if(b.kind==='factory')return factoryModel(b);if(b.kind==='warehouse')return warehouseModel(b);return shopModel(b);}
function buildingKey(s){return JSON.stringify((s.buildings||[]).map(b=>[b.id,b.kind,b.type,b.x,b.y,b.color]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))));}
function roadKey(s){return JSON.stringify((s.roads||[]).map(r=>[r.id,r.bridge,r.points]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))));}
function rounded(points){const out=[];for(const p of points||[]){if(!Number.isFinite(p?.x)||!Number.isFinite(p?.y))continue;if(!out.length||Math.hypot(p.x-out.at(-1).x,p.y-out.at(-1).y)>.6)out.push({x:p.x,y:p.y});}return out;}
function ribbon(points,width,y,mat,thickness=.12){if(points.length<2)return null;const verts=[],idx=[];for(let i=0;i<points.length;i++){const p=points[i],a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)],dx=b.x-a.x,dz=b.y-a.y,l=Math.hypot(dx,dz)||1,nx=-dz/l,nz=dx/l;verts.push(p.x+nx*width/2,y,p.y+nz*width/2,p.x-nx*width/2,y,p.y-nz*width/2);if(i){const q=(i-1)*2,r=i*2;idx.push(q,q+1,r,r,r+1,q+1);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));geo.setIndex(idx);geo.computeVertexNormals();const m=new THREE.Mesh(geo,mat);m.receiveShadow=true;m.renderOrder=2;return m;}
function roadMesh(r){const g=new THREE.Group(),p=rounded(r.points);if(p.length<2)return g;const asphalt=material('#353b3c',.92),shoulder=material('#6b7370',.98),line=material('#e9ebe5',.7),curb=material('#a0a6a1',.75);const isBridge=!!r.bridge||p.some(q=>Math.abs(q.y-riverY(q.x))<43);const sh=ribbon(p,isBridge?30:36,.58,shoulder);if(sh)g.add(sh);const surf=ribbon(p,isBridge?27:28,isBridge?.84:.69,asphalt,.14);if(surf)g.add(surf);if(!isBridge){for(const side of[-1,1]){const cp=p.map(q=>({x:q.x+side*14,y:q.y}));const c=ribbon(cp,1.1,.82,curb,.16);if(c)g.add(c);}}const samples=[];for(let i=0;i<p.length-1;i++){const a=p[i],b=p[i+1],len=Math.hypot(b.x-a.x,b.y-a.y),n=Math.max(1,Math.floor(len/28));for(let j=0;j<n;j++){const t=j/n;samples.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});}}for(let i=0;i<samples.length-1;i+=2){const m=ribbon([samples[i],samples[i+1]],1.05,isBridge?.99:.82,line,.08);if(m)g.add(m);}if(isBridge){const rail=material('#a9895c',.8,.1);for(const side of[-1,1])for(let i=0;i<p.length-1;i++){const a=p[i],b=p[i+1],dx=b.x-a.x,dz=b.y-a.y,l=Math.hypot(dx,dz)||1;box(g,l,.7,.8,rail,(a.x+b.x)/2-(dz/l)*side*16,2.3,(a.y+b.y)/2+(dx/l)*side*16,-Math.atan2(dz,dx));}}return g;}
function truckMesh(){const g=new THREE.Group(),cab=material('#5d6764',.82,.12),trailer=material('#aeb5b1',.9),dark=material('#242a2a',.98),glassMat=glass('#3b5c62'),metal=material('#6c7570',.75,.18);box(g,7,6.8,7,cab,4,4.3,0);box(g,3,3.2,6.5,glassMat,7.1,5.3,0);box(g,12,7.8,7.6,trailer,-4.5,4.7,0);box(g,12.2,.6,7.9,metal,-4.5,8.8,0);for(const x of[-7,-2.5,3.8,6.4])for(const z of[-3.85,3.85]){const w=cyl(g,1.55,1.15,dark,x,1.65,z,16);w.rotation.x=Math.PI/2;}box(g,.5,1.2,.6,material('#e6d7aa',.5),7.7,4,-3.1);box(g,.5,1.2,.6,material('#e6d7aa',.5),7.7,4,3.1);return g;}
function routePoint(points,t){if(!Array.isArray(points)||points.length<2)return null;let total=0;for(let i=1;i<points.length;i++)total+=Math.hypot(points[i].x-points[i-1].x,points[i].y-points[i-1].y);if(total<.01)return points[0];let want=Math.max(0,Math.min(1,t))*total,run=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],len=Math.hypot(b.x-a.x,b.y-a.y);if(run+len>=want){const q=(want-run)/len;return{x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q};}run+=len;}return points.at(-1);}
function rebuildWorld(s){for(const g of [...root.children]){root.remove(g);g.traverse(o=>{if(o.geometry)o.geometry.dispose();});}buildingMeshes.clear();truckMeshes.clear();const roads=new THREE.Group();for(const r of s.roads||[]){const g=roadMesh(r);g.userData.road=r;roads.add(g);}root.add(roads);for(const b of s.buildings||[]){const model=makeBuilding(b),anchor=new THREE.Group();anchor.name='building-anchor-'+b.id;anchor.position.set(Number(b.x)||0,0,Number(b.y)||0);anchor.add(model);root.add(anchor);buildingMeshes.set(b.id,model);}for(const t of s.trucks||[]){const m=truckMesh();root.add(m);truckMeshes.set(t.id,m);}worldKey=buildingKey(s)+'|'+roadKey(s);}
function updateTrucks(s){for(const [id,m] of truckMeshes){const t=(s.trucks||[]).find(x=>x.id===id);if(!t||t.dead||!Array.isArray(t.route)){m.visible=false;continue;}const p=routePoint(t.route,t.t);if(!p){m.visible=false;continue;}m.visible=true;m.position.set(p.x,1,p.y);const q=routePoint(t.route,Math.min(1,t.t+.015))||p;m.rotation.y=-Math.atan2(q.y-p.y,q.x-p.x);}}
function updateSelection(s){for(const [id,m] of buildingMeshes){const selected=(s.buildings||[]).some(b=>b.id===id&&s.selected===b);m.traverse(o=>{if(!o.isMesh||!o.material?.emissive)return;o.material.emissive.setHex(selected?0x294634:0);o.material.emissiveIntensity=selected?.32:0;});}}
function init(canvas){if(renderer)return;renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',stencil:false,depth:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,innerWidth<700?1.5:2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;scene=new THREE.Scene();scene.background=new THREE.Color('#b9c6b0');scene.fog=new THREE.Fog('#b9c6b0',900,2600);root=new THREE.Group();scene.add(root);previewGroup=new THREE.Group();scene.add(previewGroup);buildingPreviewGroup=new THREE.Group();scene.add(buildingPreviewGroup);scene.add(new THREE.HemisphereLight('#f5f8f4','#536057',1.55));const sun=new THREE.DirectionalLight('#fff5dc',2);sun.position.set(-300,480,260);sun.castShadow=true;sun.shadow.mapSize.set(innerWidth<700?1024:2048,innerWidth<700?1024:2048);sun.shadow.camera.near=10;sun.shadow.camera.far=1600;sun.shadow.camera.left=-600;sun.shadow.camera.right=600;sun.shadow.camera.top=600;sun.shadow.camera.bottom=-600;scene.add(sun);const ground=material('#708762',1);box(scene,2600,2,2600,ground,0,-7,0,0,false);const terrain=material('#78996a',1);box(scene,2600,.12,2600,terrain,0,.02,0,0,false);const river=material('#65929d',.7,.05);for(let x=-1300;x<1300;x+=44){const x2=Math.min(1300,x+52),mid=(x+x2)/2,dy=riverY(x2)-riverY(x),ang=Math.atan2(dy,x2-x);box(scene,Math.hypot(x2-x,dy)+12,.65,82,river,mid,.05,(riverY(x)+riverY(x2))/2,-ang,false);}resize(viewport.width,viewport.height);}
function resize(w,h){viewport.width=Math.max(1,w||innerWidth);viewport.height=Math.max(1,h||innerHeight);renderer?.setSize(viewport.width,viewport.height,false);if(camera){camera.aspect=viewport.width/viewport.height;camera.updateProjectionMatrix();}}
function ensureCamera(){if(!camera)camera=new THREE.PerspectiveCamera(46,viewport.width/viewport.height,2,3400);const p=Math.max(.35,Math.min(1.35,target.pitch)),h=Math.cos(p)*target.distance;camera.position.set(target.x+Math.sin(target.yaw)*h,Math.sin(p)*target.distance,target.z+Math.cos(target.yaw)*h);camera.lookAt(target.x,0,target.z);}
function bounds(){const l=(WORLD_BOUNDS.maxX-WORLD_BOUNDS.minX)/2-WORLD_MARGIN;desired.x=Math.max(-l,Math.min(l,desired.x));desired.z=Math.max(-l,Math.min(l,desired.z));}
function controlCamera(dx,dy,dd=0,dyaw=0,dpitch=0){desired.x+=dx;desired.z+=dy;desired.distance=Math.max(180,Math.min(1250,desired.distance+dd));desired.yaw+=dyaw;desired.pitch=Math.max(.35,Math.min(1.35,desired.pitch+dpitch));bounds();}
function screenToWorld(x,y,w=viewport.width,h=viewport.height){ensureCamera();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(x/w*2-1,-y/h*2+1),camera);const hit=new THREE.Vector3();return ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),hit)?{x:hit.x,y:hit.z}:{x:0,y:0};}
function panScreen(dx,dy,w=viewport.width,h=viewport.height){const a=screenToWorld(w/2,h/2,w,h),b=screenToWorld(w/2-dx,h/2-dy,w,h);desired.x+=b.x-a.x;desired.z+=b.y-a.y;bounds();}
function zoomAtScreen(x,y,z,w=viewport.width,h=viewport.height){const before=screenToWorld(x,y,w,h);desired.distance=Math.max(180,Math.min(1250,620/Math.max(.55,Math.min(2.4,z))));ensureCamera();const after=screenToWorld(x,y,w,h);desired.x+=before.x-after.x;desired.z+=before.y-after.y;bounds();}
function resetCamera(){desired={x:0,z:0,yaw:0,pitch:.82,distance:620};}
function focusCamera(x,y){desired.x=Number(x)||0;desired.z=Number(y)||0;bounds();}
function clearPreview(g){while(g.children.length){const c=g.children.pop();c.traverse(o=>{if(o.geometry)o.geometry.dispose();});}}
function setPreview(path,start,end,blocked=false){if(!previewGroup)return;clearPreview(previewGroup);if(!Array.isArray(path)||path.length<2)return;const m=material(blocked?'#c65a54':'#e1b84b',.7);const mesh=ribbon(rounded(path),18,.95,m,.12);if(mesh)previewGroup.add(mesh);}
function setBuildingPreview(type,point,blocked=false){if(!buildingPreviewGroup)return;clearPreview(buildingPreviewGroup);if(!point||!type)return;const dims=type.kind==='warehouse'?{w:194,d:132}:type.kind==='factory'?{w:166,d:118}:{w:158,d:106};const m=material(blocked?'#c65a54':'#63a987',.65);m.transparent=true;m.opacity=.32;const mesh=new THREE.Mesh(new THREE.BoxGeometry(dims.w,10,dims.d),m);mesh.position.set(point.x,5,point.y);buildingPreviewGroup.add(mesh);}
function render(s,W,H,canvas=document.querySelector('#game')){if(!canvas)return;if(!renderer)init(canvas);resize(W,H);const k=buildingKey(s)+'|'+roadKey(s);if(k!==worldKey)rebuildWorld(s);updateTrucks(s);updateSelection(s);target.x+=(desired.x-target.x)*.16;target.z+=(desired.z-target.z)*.16;target.yaw+=(desired.yaw-target.yaw)*.16;target.pitch+=(desired.pitch-target.pitch)*.16;target.distance+=(desired.distance-target.distance)*.16;ensureCamera();renderer.render(scene,camera);}
export{render,setPreview,setBuildingPreview,resize,controlCamera,screenToWorld,panScreen,zoomAtScreen,resetCamera,focusCamera};
