import {TYPES,makeBuilding} from './state.js';
export const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export const length=pts=>pts.reduce((n,p,i)=>i?n+dist(pts[i-1],p):0,0);
function projectSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return{point:{x:a.x,y:a.y},distance:dist(p,a)};const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l));const point={x:a.x+dx*t,y:a.y+dy*t};return{point,distance:dist(p,point)}}
function nearestPointOnRoad(road,p){let best=null,bd=Infinity;for(let i=1;i<road.points.length;i++){const q=projectSegment(p,road.points[i-1],road.points[i]);if(q.distance<bd){bd=q.distance;best=q.point}}return best}
export const riverY=x=>420+Math.sin(x*.002)*35;
export function district(x,y){if(Math.abs(y-riverY(x))<170)return'Riverside';if(x<0&&y<180)return'Industrial';if(x>0&&y>0)return'Market Quarter';return'West End'}
export function buildingCost(s,type){const base={Steel:260,Food:220,Parts:320,Market:180,Garage:240,Builder:220,Plastics:420,Glass:500,Electronics:520,Furniture:600,Warehouse:700};return Math.round((base[type.name]||300)*Math.pow(1.12,s.buildings.length))}
export function buildingUnlock(t,s){if(t.unlock&&(s.research?.[t.unlock]||0)<t.unlockLevel)return'Requires '+t.unlock+' research Lv '+t.unlockLevel;const min={Steel:1,Food:1,Parts:2,Market:1,Garage:2,Builder:1,Plastics:1,Glass:2,Electronics:1,Furniture:2,Warehouse:2}[t.name]||1;if(s.companyLevel<min)return'Requires Company Level '+min;return null}
export function canBuild(s,type){const reason=buildingUnlock(type,s);if(reason)return reason;const cap=10+(s.research?.industry||0)*2;if(s.buildings.length>=cap)return'Company building capacity reached ('+cap+')';if(s.cash<buildingCost(s,type))return'Costs £'+buildingCost(s,type);return null}
export function placeBuilding(s,type,x,y){if(canBuild(s,type))return false;if(s.buildings.some(b=>dist(b,{x,y})<145))return false;if(Math.abs(y-riverY(x))<105)return false;const b=makeBuilding(type,x,y,crypto.randomUUID());b.district=district(x,y);s.cash-=buildingCost(s,type);s.buildings.push(b);return b}
export function spawn(s,kind,forced){const pool=TYPES.filter(t=>t.kind===kind&&(!forced||t.name===forced)&&(!t.unlock||(s.research?.[t.unlock]||0)>=t.unlockLevel));if(!pool.length)return null;let candidates=pool;if(!forced&&pool.length>1){const recent=s.buildings.slice(-2).map(b=>b.type);const filtered=pool.filter(t=>!recent.includes(t.name));if(filtered.length)candidates=filtered}const type=candidates[Math.floor(Math.random()*candidates.length)];let x=0,y=0,ok=false;const count=s.buildings.length,minRadius=count<6?170:280,maxRadius=count<6?430:Math.min(760,430+s.companyLevel*22);for(let n=0;n<300&&!ok;n++){const angle=Math.random()*Math.PI*2,radius=minRadius+Math.random()*(maxRadius-minRadius);x=Math.cos(angle)*radius+(Math.random()-.5)*90;y=Math.sin(angle)*radius+(Math.random()-.5)*90;const river=riverY(x);if(Math.abs(y-river)<105)y+=y<river?-120:120;ok=s.buildings.every(b=>dist(b,{x,y})>145)}if(!ok)return null;const b=makeBuilding(type,x,y,crypto.randomUUID());b.district=district(x,y);s.buildings.push(b);return b}
export function seed(s){for(const t of['Steel','Food','Parts'])spawn(s,'factory',t);for(const t of['Market','Garage','Builder'])spawn(s,'shop',t)}
export function pointOnRoute(points,t){const total=length(points);if(!total)return points[0];let want=total*Math.max(0,Math.min(1,t)),run=0;for(let i=1;i<points.length;i++){const seg=dist(points[i-1],points[i]);if(run+seg>=want){const q=(want-run)/seg;return{x:points[i-1].x+(points[i].x-points[i-1].x)*q,y:points[i-1].y+(points[i].y-points[i-1].y)*q}}run+=seg}return points.at(-1)}
export function nearestBuilding(s,p){let best=null,bd=42;for(const b of s.buildings){const d=dist(b,p);if(d<bd){bd=d;best=b}}return best}
function projectOnPolyline(points,p){let best=null,run=0;for(let i=1;i<points.length;i++){const q=projectSegment(p,points[i-1],points[i]);if(!best||q.distance<best.distance)best={...q,segment:i-1,along:run+dist(points[i-1],q.point)};run+=dist(points[i-1],points[i])}return best}
export function nearestRoad(s,p){let best=null;for(const road of s.roads||[]){if(!road?.points||road.points.length<2)continue;const q=projectOnPolyline(road.points,p);if(q&&(!best||q.distance<best.distance))best={x:q.point.x,y:q.point.y,road,distance:q.distance,segment:q.segment,along:q.along}}return best&&best.distance<=34?best:null}
function buildingConnectionPoint(building,target){const dx=target.x-building.x,dy=target.y-building.y;const len=Math.hypot(dx,dy)||1;const radius=Math.max(26,Math.max(building.r||25,25)+9);return{x:building.x+dx/len*radius,y:building.y+dy/len*radius,building}}
export function snapRoadPoint(s,p,max=42){const q=nearestRoad(s,p);if(!q||q.distance>max)return null;return{x:q.x,y:q.y,road:q.road,distance:q.distance}}
export function roadPreview(s,a,b){const resolve=p=>{const road=snapRoadPoint(s,p,42);if(road)return road;const building=nearestBuilding(s,p);if(building&&dist(building,p)<=48)return{...buildingConnectionPoint(building,p),distance:dist(building,p),building};return{x:p.x,y:p.y,distance:Infinity}};const start=resolve(a),end=resolve(b);return{path:[{x:start.x,y:start.y},{x:end.x,y:end.y}],start,end,snappedStart:Number.isFinite(start.distance),snappedEnd:Number.isFinite(end.distance),connectsBuilding:!!start.building||!!end.building,connectsRoad:!!start.road||!!end.road}}
export function snap(s,p){const b=nearestBuilding(s,p);if(b)return b;const r=nearestRoad(s,p);return r||p}
function segmentIntersection(a,b,c,d){const ab={x:b.x-a.x,y:b.y-a.y},cd={x:d.x-c.x,y:d.y-c.y},cross=(u,v)=>u.x*v.y-u.y*v.x,den=cross(ab,cd),ac={x:c.x-a.x,y:c.y-a.y};if(Math.abs(den)<1e-9)return null;const t=cross(ac,cd)/den,u=cross(ac,ab)/den;if(t<-.000001||t>1.000001||u<-.000001||u>1.000001)return null;return{x:a.x+ab.x*t,y:a.y+ab.y*t,t,u}}
function addNode(nodes,p){let n=nodes.find(x=>dist(x,p)<2.5);if(!n){n={x:p.x,y:p.y};nodes.push(n)}return n}
function roadPointParameter(a,b,p){return projectSegment(p,a,b).distance}
export function roadNetwork(s){const valid=(s.roads||[]).filter(r=>r?.points?.length>=2),nodes=[],edges=[],marks=new Map();for(const road of valid){const segments=road.points.slice(1).map(()=>[]);marks.set(road,segments);for(let i=1;i<road.points.length;i++){segments[i-1].push(addNode(nodes,road.points[i-1]));segments[i-1].push(addNode(nodes,road.points[i]))}}for(let ri=0;ri<valid.length;ri++){const aRoad=valid[ri];for(let qi=ri;qi<valid.length;qi++){const bRoad=valid[qi];for(let i=1;i<aRoad.points.length;i++){const a=aRoad.points[i-1],b=aRoad.points[i],first=aRoad===bRoad?i:1;for(let j=first;j<bRoad.points.length;j++){if(aRoad===bRoad&&i===j)continue;const hit=segmentIntersection(a,b,bRoad.points[j-1],bRoad.points[j]);if(!hit)continue;const n=addNode(nodes,hit);marks.get(aRoad)[i-1].push(n);marks.get(bRoad)[j-1].push(n)}}}}for(const road of valid){for(let i=0;i<road.points.length-1;i++){const a=road.points[i],b=road.points[i+1],list=[...new Set(marks.get(road)[i])].sort((u,v)=>roadPointParameter(a,b,u)-roadPointParameter(a,b,v));for(let j=1;j<list.length;j++){const u=list[j-1],v=list[j],d=dist(u,v);if(d>1)edges.push({a:u,b:v,d,road})}}}const adjacency=new Map(nodes.map(n=>[n,[]]));for(const e of edges){adjacency.get(e.a).push({node:e.b,d:e.d,road:e.road});adjacency.get(e.b).push({node:e.a,d:e.d,road:e.road})}return{nodes,edges,adjacency}}
function nearestNetworkPoint(network,p){let best=null;for(const e of network.edges){const q=projectSegment(p,e.a,e.b);if(!best||q.distance<best.distance)best={edge:e,point:q.point,distance:q.distance}}return best}
function shortestRoadPath(network,a,b){const queue=[{node:a,d:0}],best=new Map([[a,0]]),prev=new Map();while(queue.length){queue.sort((x,y)=>x.d-y.d);const cur=queue.shift();if(cur.d!==best.get(cur.node))continue;if(cur.node===b)break;for(const nx of network.adjacency.get(cur.node)||[]){const nd=cur.d+nx.d;if(nd<(best.get(nx.node)??Infinity)){best.set(nx.node,nd);prev.set(nx.node,cur.node);queue.push({node:nx.node,d:nd})}}}if(!best.has(b))return null;const path=[];let n=b;while(n){path.unshift(n);n=prev.get(n)}return{path,distance:best.get(b)}}
export function roadAttachment(s,building){if(!building)return null;const limit=Math.max(34,(building.r||25)+12);let best=null;for(const road of s.roads||[]){if(!road?.points||road.points.length<2)continue;for(const point of [road.points[0],road.points[road.points.length-1]]){const distance=dist(building,point);if(distance<=limit&&(!best||distance<best.distance))best={road,point:{x:point.x,y:point.y},distance}}}return best}
export function routeOnRoadNetwork(s,a,b){const network=roadNetwork(s);if(!network.edges.length)return null;const resolveEndpoint=value=>{const attachment=roadAttachment(s,value);if(attachment)return{point:attachment.point,distance:0,attachment};const hit=nearestNetworkPoint(network,value);return hit||null},sa=resolveEndpoint(a),sb=resolveEndpoint(b);if(!sa||!sb)return null;const start=addNode([],sa.point),end=addNode([],sb.point),adjacency=new Map(network.nodes.map(n=>[n,[...(network.adjacency.get(n)||[])]]));adjacency.set(start,[]);adjacency.set(end,[]);const connect=(virtual,hit)=>{const e=hit.edge,da=dist(virtual,e.a),db=dist(virtual,e.b);adjacency.get(virtual).push({node:e.a,d:da,road:e.road},{node:e.b,d:db,road:e.road});adjacency.get(e.a).push({node:virtual,d:da,road:e.road});adjacency.get(e.b).push({node:virtual,d:db,road:e.road})};if(sa.attachment){const node=addNode(network.nodes,sa.point);adjacency.set(start,[...(network.adjacency.get(node)||[])]);for(const nx of network.adjacency.get(node)||[])adjacency.get(nx.node).push({node:start,d:nx.d,road:nx.road})}else connect(start,sa);if(sb.attachment){const node=addNode(network.nodes,sb.point);adjacency.set(end,[...(network.adjacency.get(node)||[])]);for(const nx of network.adjacency.get(node)||[])adjacency.get(nx.node).push({node:end,d:nx.d,road:nx.road})}else connect(end,sb);const result=shortestRoadPath({adjacency},start,end);if(!result||result.path.length<2)return null;return{points:result.path.map(p=>({x:p.x,y:p.y})),distance:result.distance,networkDistance:result.distance,start:{x:sa.point.x,y:sa.point.y},end:{x:sb.point.x,y:sb.point.y}}}
export function roadPath(s,a,b){const start=snap(s,a),end=snap(s,b);if(dist(start,end)<8)return[start,end];const existing=routeOnRoadNetwork(s,start,end);return existing?existing.points:null}
function roadDistance(a,b){let best=Infinity;for(let i=1;i<a.points.length;i++){const pa=a.points[i-1],pb=a.points[i];for(let j=1;j<b.length;j++){const pc=b[j-1],pd=b[j];best=Math.min(best,projectSegment(pa,pc,pd).distance,projectSegment(pb,pc,pd).distance,projectSegment(pc,pa,pb).distance,projectSegment(pd,pa,pb).distance)}}return best}
function pointSegmentDistance(p,a,b){return projectSegment(p,a,b).distance}
export function addRoad(s,points){if(!Array.isArray(points)||points.length<2)return false;const clean=points.filter((p,i)=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&(!i||dist(p,points[i-1])>8));if(clean.length<2)return false;const roadLength=length(clean);if(roadLength<18)return false;for(let i=1;i<clean.length;i++){const a=clean[i-1],z=clean[i];for(const b of s.buildings||[]){const clearance=(b.r||25)+7;const aNear=dist(b,a)<=clearance+7,zNear=dist(b,z)<=clearance+7;if(pointSegmentDistance(b,a,z)<clearance&&!aNear&&!zNear)return false;}}const cost=Math.max(1,Math.ceil(roadLength/90)),cashCost=cost*2;if(s.roadBudget<cost||s.cash<cashCost)return false;if((s.roads||[]).some(r=>roadDistance(r,clean)<10&&Math.abs(length(r.points)-roadLength)<18))return false;const bridge=clean.some((p,i)=>i&&Math.abs(p.y-riverY(p.x))<45);s.roadBudget-=cost;s.cash-=cashCost;s.roads.push({id:crypto.randomUUID(),points:clean,age:0,bridge,condition:1});return true}
export function eraseRoad(s,p){let hit=null,bd=16;for(const r of s.roads||[]){const q=projectOnPolyline(r.points,p);if(q&&q.distance<bd){bd=q.distance;hit=r}}if(!hit)return false;s.roads=s.roads.filter(r=>r!==hit);return true}
