import {TYPES,makeBuilding} from './state.js';
const newId=()=>globalThis.crypto?.randomUUID?.()||'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
export const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export const length=pts=>pts.reduce((n,p,i)=>i?n+dist(pts[i-1],p):0,0);
const finitePoint=p=>p&&Number.isFinite(Number(p.x))&&Number.isFinite(Number(p.y));
const safePoint=p=>({x:Number(p.x),y:Number(p.y)});
const validRoadPoints=(points,minLength=12)=>{const clean=[];for(const p of points||[]){if(!finitePoint(p))continue;const q=safePoint(p);if(!clean.length||dist(clean.at(-1),q)>2)clean.push(q)}return clean.length>=2&&length(clean)>=minLength?clean:null};
function projectSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return{point:{x:a.x,y:a.y},distance:dist(p,a)};const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l));const point={x:a.x+dx*t,y:a.y+dy*t};return{point,distance:dist(p,point)}}
function nearestPointOnRoad(road,p){let best=null,bd=Infinity;for(let i=1;i<road.points.length;i++){const q=projectSegment(p,road.points[i-1],road.points[i]);if(q.distance<bd){bd=q.distance;best=q.point}}return best}
export const riverY=x=>420+Math.sin(x*.002)*35;
export const WORLD_SIZE=2600;
export const WORLD_HALF_SIZE=WORLD_SIZE/2;
export const WORLD_BOUNDS=Object.freeze({minX:-WORLD_HALF_SIZE,maxX:WORLD_HALF_SIZE,minY:-WORLD_HALF_SIZE,maxY:WORLD_HALF_SIZE});
export const WORLD_CONSTRUCTION_MARGIN=24;
export const WORLD_MARGIN=WORLD_CONSTRUCTION_MARGIN;
export const WORLD_EDGE_SNAP_DISTANCE=52;
export function isInsideWorldBounds(p,margin=WORLD_MARGIN){return finitePoint(p)&&Number(p.x)>=WORLD_BOUNDS.minX+margin&&Number(p.x)<=WORLD_BOUNDS.maxX-margin&&Number(p.y)>=WORLD_BOUNDS.minY+margin&&Number(p.y)<=WORLD_BOUNDS.maxY-margin}
function roadWithinWorldBounds(points,margin=WORLD_MARGIN){const clean=validRoadPoints(points,0);return !!clean&&clean.every(p=>isInsideWorldBounds(p,margin))}
export function validateRoadGeometry(points){const clean=validRoadPoints(points,12);if(!clean)return{ok:false,reason:'Road is too short or invalid',points:[]};if(!roadWithinWorldBounds(clean))return{ok:false,reason:'Road is outside the playable area',points:clean};return{ok:true,reason:null,points:clean}}
export function district(x,y){if(Math.abs(y-riverY(x))<170)return'Riverside';if(x<0&&y<180)return'Industrial';if(x>0&&y>0)return'Market Quarter';return'West End'}
export function buildingCost(s,type){const base={Steel:260,Food:220,Parts:320,Market:180,Garage:240,Builder:220,Plastics:420,Glass:500,Electronics:520,Furniture:600,Warehouse:700};return Math.round((base[type.name]||300)*Math.pow(1.12,s.buildings.length))}
export function buildingUnlock(t,s){if(t.unlock&&(s.research?.[t.unlock]||0)<t.unlockLevel)return'Requires '+t.unlock+' research Lv '+t.unlockLevel;const min={Steel:1,Food:1,Parts:2,Market:1,Garage:2,Builder:1,Plastics:1,Glass:2,Electronics:1,Furniture:2,Warehouse:2}[t.name]||1;if(s.companyLevel<min)return'Requires Company Level '+min;return null}
export function canBuild(s,type){const reason=buildingUnlock(type,s);if(reason)return reason;const cap=10+(s.research?.industry||0)*2;if(s.buildings.length>=cap)return'Company building capacity reached ('+cap+')';if(s.cash<buildingCost(s,type))return'Costs £'+buildingCost(s,type);return null}
export function canPlaceBuildingAt(s,type,x,y){const reason=canBuild(s,type);if(reason)return reason;if(!Number.isFinite(x)||!Number.isFinite(y))return'Invalid placement';if(s.buildings.some(b=>dist(b,{x,y})<145))return'Too close to another building';if(Math.abs(y-riverY(x))<105)return'Too close to the river';return null}
export function placeBuilding(s,type,x,y){if(canPlaceBuildingAt(s,type,x,y))return false;const b=makeBuilding(type,x,y,newId());b.district=district(x,y);s.cash-=buildingCost(s,type);s.buildings.push(b);return b}
export function spawn(s,kind,forced){const pool=TYPES.filter(t=>t.kind===kind&&(!forced||t.name===forced)&&(!t.unlock||(s.research?.[t.unlock]||0)>=t.unlockLevel));if(!pool.length)return null;let candidates=pool;if(!forced&&pool.length>1){const recent=s.buildings.slice(-2).map(b=>b.type);const filtered=pool.filter(t=>!recent.includes(t.name));if(filtered.length)candidates=filtered}const type=candidates[Math.floor(Math.random()*candidates.length)];let x=0,y=0,ok=false;const count=s.buildings.length,minRadius=count<6?170:280,maxRadius=count<6?430:Math.min(760,430+s.companyLevel*22);for(let n=0;n<300&&!ok;n++){const angle=Math.random()*Math.PI*2,radius=minRadius+Math.random()*(maxRadius-minRadius);x=Math.cos(angle)*radius+(Math.random()-.5)*90;y=Math.sin(angle)*radius+(Math.random()-.5)*90;const river=riverY(x);if(Math.abs(y-river)<105)y+=y<river?-120:120;ok=s.buildings.every(b=>dist(b,{x,y})>145)}if(!ok)return null;const b=makeBuilding(type,x,y,newId());b.district=district(x,y);s.buildings.push(b);return b}
export function seed(s){for(const t of['Steel','Food','Parts'])spawn(s,'factory',t);for(const t of['Market','Garage','Builder'])spawn(s,'shop',t)}
export function pointOnRoute(points,t){const total=length(points);if(!total)return points[0];let want=total*Math.max(0,Math.min(1,t)),run=0;for(let i=1;i<points.length;i++){const seg=dist(points[i-1],points[i]);if(run+seg>=want){const q=(want-run)/seg;return{x:points[i-1].x+(points[i].x-points[i-1].x)*q,y:points[i-1].y+(points[i].y-points[i-1].y)*q}}run+=seg}return points.at(-1)}
export function nearestBuilding(s,p){let best=null,bd=58;for(const b of s.buildings){const d=dist(b,p);if(d<bd){bd=d;best=b}}return best}
export function roadBuildingTarget(s,p){let best=null,bd=Infinity;for(const b of s.buildings||[]){const hit=Math.max(52,(b.r||25)+26);const d=dist(b,p);if(d<=hit&&d<bd){bd=d;best=b}}return best}
function projectOnPolyline(points,p){let best=null,run=0;for(let i=1;i<points.length;i++){const q=projectSegment(p,points[i-1],points[i]);if(!best||q.distance<best.distance)best={...q,segment:i-1,along:run+dist(points[i-1],q.point)};run+=dist(points[i-1],points[i])}return best}
export function nearestRoad(s,p){let best=null;for(const road of s.roads||[]){const points=validRoadPoints(road?.points,0);if(!points)continue;const q=projectOnPolyline(points,p);if(q&&(!best||q.distance<best.distance))best={x:q.point.x,y:q.point.y,road,distance:q.distance,segment:q.segment,along:q.along}}return best&&best.distance<=46?best:null}
function buildingFootprintRadius(building){const footprint=building?.kind==='warehouse'?48:building?.kind==='factory'?39:35;return Math.max(26,(building?.r||25)+9,footprint+5)}
function buildingConnectionPoint(building,target){const dx=target.x-building.x,dy=target.y-building.y,len=Math.hypot(dx,dy)||1,radius=buildingFootprintRadius(building);return{x:building.x+dx/len*radius,y:building.y+dy/len*radius,building,distance:0}}
function endpointSegmentBlocked(building,a,b,side){if(!building)return false;const ax=a.x-building.x,ay=a.y-building.y,bx=b.x-building.x,by=b.y-building.y,aRadius=Math.hypot(ax,ay),bRadius=Math.hypot(bx,by);const outward=side==='start'?ax*(b.x-a.x)+ay*(b.y-a.y):bx*(a.x-b.x)+by*(a.y-b.y);const connectionRadius=buildingFootprintRadius(building);const outside=side==='start'?aRadius>=connectionRadius-.001:bRadius>=connectionRadius-.001;return outside&&outward<0}
function resolveRoadEndpoint(s,value){if(value?.building&&Number.isFinite(value.building.x))return buildingConnectionPoint(value.building,value);const building=nearestBuilding(s,value);if(building&&dist(building,value)<=48)return buildingConnectionPoint(building,value);const road=snapRoadPoint(s,value,42);return road||{x:value.x,y:value.y,distance:Infinity}}
export function snapRoadPoint(s,p,max=42){const q=nearestRoad(s,p);if(!q||q.distance>max)return null;return{x:q.x,y:q.y,road:q.road,distance:q.distance}}
export function snap(s,p){const b=nearestBuilding(s,p);if(b)return b;const r=nearestRoad(s,p);return r||p}
function segmentIntersection(a,b,c,d){const ab={x:b.x-a.x,y:b.y-a.y},cd={x:d.x-c.x,y:d.y-c.y},cross=(u,v)=>u.x*v.y-u.y*v.x,den=cross(ab,cd),ac={x:c.x-a.x,y:c.y-a.y};if(Math.abs(den)<1e-9)return null;const t=cross(ac,cd)/den,u=cross(ac,ab)/den;if(t<-.000001||t>1.000001||u<-.000001||u>1.000001)return null;return{x:a.x+ab.x*t,y:a.y+ab.y*t,t,u}}
function addNode(nodes,p){let n=nodes.find(x=>dist(x,p)<2.5);if(!n){n={x:p.x,y:p.y};nodes.push(n)}return n}
function roadPointParameter(a,b,p){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return 0;return Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l))}
function isRoadJunctionNode(node,links){if(links.length>=3)return true;if(links.length!==2)return false;const a=links[0].node,b=links[1].node;const avx=a.x-node.x,avy=a.y-node.y,bvx=b.x-node.x,bvy=b.y-node.y;const al=Math.hypot(avx,avy),bl=Math.hypot(bvx,bvy);if(al<1e-9||bl<1e-9)return false;const alignment=Math.abs((avx*bvx+avy*bvy)/(al*bl));return alignment<0.985}
export function roadNetwork(s,extraPoints=[]){const valid=(s.roads||[]).map(r=>({...r,points:validRoadPoints(r?.points,0)})).filter(r=>r.points?.length>=2&&roadWithinWorldBounds(r.points)),nodes=[],edges=[],marks=new Map();for(const road of valid){const segments=road.points.slice(1).map(()=>[]);marks.set(road,segments);for(let i=1;i<road.points.length;i++){segments[i-1].push(addNode(nodes,road.points[i-1]));segments[i-1].push(addNode(nodes,road.points[i]));}}for(let ri=0;ri<valid.length;ri++){const aRoad=valid[ri];for(let qi=ri;qi<valid.length;qi++){const bRoad=valid[qi];for(let i=1;i<aRoad.points.length;i++){const a=aRoad.points[i-1],b=aRoad.points[i],first=aRoad===bRoad?i:1;for(let j=first;j<bRoad.points.length;j++){if(aRoad===bRoad&&i===j)continue;const hit=segmentIntersection(a,b,bRoad.points[j-1],bRoad.points[j]);if(!hit)continue;const n=addNode(nodes,hit);marks.get(aRoad)[i-1].push(n);marks.get(bRoad)[j-1].push(n)}}}}const junctionTolerance=6;for(let ri=0;ri<valid.length;ri++)for(let qi=ri;qi<valid.length;qi++){const aRoad=valid[ri],bRoad=valid[qi];const aEnds=[{index:0,point:aRoad.points[0]},{index:aRoad.points.length-1,point:aRoad.points.at(-1)}];const bEnds=[{index:0,point:bRoad.points[0]},{index:bRoad.points.length-1,point:bRoad.points.at(-1)}];for(const aEnd of aEnds)for(const bEnd of bEnds){if(aRoad===bRoad)continue;if(dist(aEnd.point,bEnd.point)>junctionTolerance)continue;const n=addNode(nodes,{x:(aEnd.point.x+bEnd.point.x)/2,y:(aEnd.point.y+bEnd.point.y)/2});const aSeg=aEnd.index===0?0:aRoad.points.length-2;const bSeg=bEnd.index===0?0:bRoad.points.length-2;marks.get(aRoad)[aSeg].push(n);marks.get(bRoad)[bSeg].push(n);}for(const aEnd of aEnds){for(let j=1;j<bRoad.points.length;j++){if(aRoad===bRoad)continue;const q=projectSegment(aEnd.point,bRoad.points[j-1],bRoad.points[j]);if(q.distance>junctionTolerance)continue;const n=addNode(nodes,q.point);marks.get(aRoad)[aEnd.index===0?0:aRoad.points.length-2].push(n);marks.get(bRoad)[j-1].push(n);}}}for(const p of extraPoints||[]){if(!finitePoint(p))continue;let best=null;for(const road of valid)for(let i=1;i<road.points.length;i++){const q=projectSegment(p,road.points[i-1],road.points[i]);if(!best||q.distance<best.distance)best={road,segment:i-1,point:q.point,distance:q.distance}}if(best){const n=addNode(nodes,best.point);marks.get(best.road)[best.segment].push(n)}}for(const road of valid)for(let i=0;i<road.points.length-1;i++){const a=road.points[i],b=road.points[i+1],list=[...new Set(marks.get(road)[i])].sort((u,v)=>roadPointParameter(a,b,u)-roadPointParameter(a,b,v));for(let j=1;j<list.length;j++){const u=list[j-1],v=list[j],d=dist(u,v);if(d>0.5)edges.push({a:u,b:v,d,road});}}const adjacency=new Map(nodes.map(n=>[n,[]]));for(const e of edges){adjacency.get(e.a).push({node:e.b,d:e.d,road:e.road});adjacency.get(e.b).push({node:e.a,d:e.d,road:e.road})}const junctions=nodes.filter(n=>isRoadJunctionNode(n,adjacency.get(n)||[]));return{nodes,edges,adjacency,junctions}}
export function roadTrafficMetrics(s){
  const segments=[];const byRoad=new Map();
  for(const road of s.roads||[]){if(!Array.isArray(road.points)||road.points.length<2)continue;const roadSegments=[];const condition=Math.max(0,Math.min(1,Number.isFinite(road.condition)?road.condition:1));for(let i=1;i<road.points.length;i++){const a=road.points[i-1],b=road.points[i],segmentLength=dist(a,b);if(segmentLength<1)continue;const lanes=2;const capacity=Math.max(2,Math.ceil(segmentLength/120)*lanes);const segment={road,index:i-1,a,b,length:segmentLength,lanes,capacity,load:0,congestion:0,speedMultiplier:Math.max(.35,.7+.3*condition)};segments.push(segment);roadSegments.push(segment)}byRoad.set(road.id,roadSegments)}
  const nearest=(p,maxDistance=48)=>{let best=null,bd=maxDistance;for(const segment of segments){const q=projectSegment(p,segment.a,segment.b);if(q.distance<bd){bd=q.distance;best={segment,projection:q}}}return best};return{segments,byRoad,nearest}}
export function roadTrafficSegment(s,p,maxDistance=48){return roadTrafficMetrics(s).nearest(p,maxDistance)}
export function roadTopology(s){const network=roadNetwork(s);const boundaryMinX=WORLD_BOUNDS.minX+WORLD_MARGIN,boundaryMaxX=WORLD_BOUNDS.maxX-WORLD_MARGIN,boundaryMinY=WORLD_BOUNDS.minY+WORLD_MARGIN,boundaryMaxY=WORLD_BOUNDS.maxY-WORLD_MARGIN,boundaryTolerance=3;const topologyNodes=network.nodes.map((node,index)=>{const links=network.adjacency.get(node)||[],roadIds=[...new Set(links.map(link=>link.road?.id).filter(Boolean))],degree=links.length,boundary=Math.abs(node.x-boundaryMinX)<=boundaryTolerance||Math.abs(node.x-boundaryMaxX)<=boundaryTolerance||Math.abs(node.y-boundaryMinY)<=boundaryTolerance||Math.abs(node.y-boundaryMaxY)<=boundaryTolerance,junction=isRoadJunctionNode(node,links);return{id:index,x:node.x,y:node.y,degree,roadIds,boundary,junction,type:junction?(boundary?'boundary-junction':'junction'):(boundary?'boundary':degree===1?'endpoint':'node')}});const junctions=topologyNodes.filter(node=>node.junction);return{...network,topologyNodes,topologyJunctions:junctions,boundaryNodes:topologyNodes.filter(node=>node.boundary),threeWayJunctions:junctions.filter(node=>node.degree===3),fourWayJunctions:junctions.filter(node=>node.degree>=4)}}
function shortestRoadPath(network,a,b){const queue=[{node:a,d:0}],best=new Map([[a,0]]),prev=new Map();while(queue.length){queue.sort((x,y)=>x.d-y.d);const cur=queue.shift();if(cur.d!==best.get(cur.node))continue;if(cur.node===b)break;for(const nx of network.adjacency.get(cur.node)||[]){const nd=cur.d+nx.d;if(nd<(best.get(nx.node)??Infinity)){best.set(nx.node,nd);prev.set(nx.node,cur.node);queue.push({node:nx.node,d:nd})}}}if(!best.has(b))return null;const path=[];let n=b;while(n){path.unshift(n);n=prev.get(n)}return{path,distance:best.get(b)}}
export function roadAttachment(s,building){if(!building)return null;const limit=Math.max(42,(building.r||25)+18);let best=null;for(const road of s.roads||[]){const points=validRoadPoints(road?.points,0);if(!points)continue;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],q=projectSegment(building,a,b);if(q.distance<=limit&&(!best||q.distance<best.distance))best={road,point:{x:q.point.x,y:q.point.y},distance:q.distance,segment:i-1}}}return best}
function nearestGraphNode(network,p){let best=null,bd=Infinity;for(const n of network.nodes){const d=dist(n,p);if(d<bd){bd=d;best=n}}return best&&bd<=2.5?best:null}
export function routeOnRoadNetwork(s,a,b){const aa=roadAttachment(s,a),bb=roadAttachment(s,b);if(!aa||!bb)return null;const network=roadNetwork(s,[aa.point,bb.point]),start=nearestGraphNode(network,aa.point),end=nearestGraphNode(network,bb.point);if(!start||!end)return null;const result=shortestRoadPath(network,start,end);if(!result||result.path.length<2)return null;return{points:result.path.map(p=>({x:p.x,y:p.y})),distance:result.distance,networkDistance:result.distance,start:{x:aa.point.x,y:aa.point.y},end:{x:bb.point.x,y:bb.point.y}}}
function pointSegmentDistance(p,a,b){return projectSegment(p,a,b).distance}
export function roadPath(s,a,b){const start=snap(s,a),end=snap(s,b);if(dist(start,end)<8)return[start,end];const existing=routeOnRoadNetwork(s,start,end);return existing?existing.points:null}
