import {TYPES,makeBuilding} from './state.js';
import {buildLaneGraph,findLaneRoute,laneRouteToNodePath,laneRouteGeometry} from './laneGraph.js';
const newId=()=>globalThis.crypto?.randomUUID?.()||'id-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
export const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export const length=pts=>pts.reduce((n,p,i)=>i?n+dist(pts[i-1],p):0);
const finitePoint=p=>p&&Number.isFinite(Number(p.x))&&Number.isFinite(Number(p.y));
const safePoint=p=>({x:Number(p.x),y:Number(p.y)});
const validRoadPoints=(points,minLength=12)=>{const clean=[];for(const p of points||[]){if(!finitePoint(p))continue;const q=safePoint(p);if(!clean.length||dist(clean.at(-1),q)>2)clean.push(q)}return clean.length>=2&&length(clean)>=minLength?clean:null};
function projectSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy;if(!l)return{point:{x:a.x,y:a.y},distance:dist(p,a)};const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l));const point={x:a.x+dx*t,y:a.y+dy*t};return{point,distance:dist(p,point)}}
function nearestPointOnRoad(road,p){let best=null,bd=Infinity;for(let i=1;i<road.points.length;i++){const q=projectSegment(p,road.points[i-1],road.points[i]);if(q.distance<bd){bd=q.distance;best=q.point}}return best}
export const riverY=x=>420+Math.sin(x*.002)*35;
export const WORLD_SIZE=2600;
export const WORLD_HALF_SIZE=WORLD_SIZE/2;
export const WORLD_BOUNDS=Object.freeze({minX:-WORLD_HALF_SIZE,maxX:WORLD_HALF_SIZE,minY:-WORLD_HALF_SIZE,maxY:WORLD_HALF_SIZE});
export const WORLD_CONSTRUCTION_MARGIN=24;
export const WORLD_MARGIN=WORLD_CONSTRUCTION_MARGIN;
export const WORLD_EDGE_SNAP_DISTANCE=52;
export function isInsideWorldBounds(p,margin=WORLD_MARGIN){return finitePoint(p)&&Number(p.x)>=WORLD_BOUNDS.minX+margin&&Number(p.x)<=WORLD_BOUNDS.maxX-margin&&Number(p.y)>=WORLD_BOUNDS.minY+margin&&Number(p.y)<=WORLD_BOUNDS.maxY-margin}
function roadWithinWorldBounds(points,margin=WORLD_MARGIN){const clean=validRoadPoints(points,0);return !!clean&&clean.every(p=>isInsideWorldBounds(p,margin))}
export function validateRoadGeometry(points){const clean=validRoadPoints(points,12);if(!clean)return{ok:false,reason:'Road is too short or invalid',points:[]};if(!roadWithinWorldBounds(clean))return{ok:false,reason:'Road is outside the playable area',points:clean};return{ok:true,reason:null,points:clean}}
export function district(x,y){if(Math.abs(y-riverY(x))<170)return'Riverside';if(x<0&&y<180)return'Industrial';if(x>0&&y>0)return'Market Quarter';return'West End'}
export function buildingCost(s,type){const base={Steel:260,Food:220,Parts:320,Market:180,Garage:240,Builder:220,Plastics:420,Glass:500,Electronics:520,Furniture:600,Warehouse:700};return Math.round((base[type.name]||300)*Math.pow(1.12,s.buildings.length))}
export function buildingUnlock(t,s){if(t.unlock&&(s.research?.[t.unlock]||0)<t.unlockLevel)return'Requires '+t.unlock+' research Lv '+t.unlockLevel;const min={Steel:1,Food:1,Parts:2,Market:1,Garage:2,Builder:1,Plastics:1,Glass:2,Electronics:1,Furniture:2,Warehouse:2}[t.name]||1;if(s.companyLevel<min)return'Requires Company Level '+min;return null}
export function canBuild(s,type){const reason=buildingUnlock(type,s);if(reason)return reason;const cap=10+(s.research?.industry||0)*2;if(s.buildings.length>=cap)return'Company building capacity reached ('+cap+')';if(s.cash<buildingCost(s,type))return'Costs £'+buildingCost(s,type);return null}
export function buildingFootprint(building){if(building?.kind==='warehouse')return{halfWidth:48,halfDepth:33};if(building?.kind==='factory')return{halfWidth:39,halfDepth:31};return{halfWidth:35,halfDepth:28}}
export function buildingHitbox(building,tolerance=0){const footprint=buildingFootprint(building);return{minX:building.x-footprint.halfWidth-tolerance,maxX:building.x+footprint.halfWidth+tolerance,minY:building.y-footprint.halfDepth-tolerance,maxY:building.y+footprint.halfDepth+tolerance}}
function buildingOverlap(a,b,clearance=18){const af=buildingFootprint(a),bf=buildingFootprint(b);return Math.abs(Number(a.x)-Number(b.x))<af.halfWidth+bf.halfWidth+clearance&&Math.abs(Number(a.y)-Number(b.y))<af.halfDepth+bf.halfDepth+clearance}
export function canPlaceBuildingAt(s,type,x,y){const reason=canBuild(s,type);if(reason)return reason;return canPlaceBuildingPhysically(s,type,x,y)}
export function canPlaceBuildingPhysically(s,type,x,y){if(!Number.isFinite(x)||!Number.isFinite(y))return'Invalid placement';const candidate={kind:type.kind,x,y};const f=buildingFootprint(candidate);if(!isInsideWorldBounds({x,y},Math.max(WORLD_MARGIN,f.halfWidth+4,f.halfDepth+4)))return'Outside the playable area';for(const b of s.buildings||[])if(buildingOverlap(candidate,b))return'Too close to another building';if(Math.abs(y-riverY(x))<105+Math.max(f.halfDepth,f.halfWidth)*.18)return'Too close to the river';return null}
function canPlaceGeneratedBuilding(s,type,x,y){return canPlaceBuildingPhysically(s,type,x,y)}
export function buildingPlacementTarget(s,type,p){
  if(!finitePoint(p)||!type)return null;
  const f=buildingFootprint({kind:type.kind}), raw={x:Number(p.x),y:Number(p.y)}, road=nearestRoad(s,raw), building=nearestBuilding(s,raw), candidates=[];
  if(road){const vx=raw.x-road.x,vy=raw.y-road.y,len=Math.hypot(vx,vy)||1,ux=vx/len,uy=vy/len,support=Math.abs(ux)>Math.abs(uy)?f.halfWidth:f.halfDepth;candidates.push({point:{x:road.x+ux*(support+10),y:road.y+uy*(support+10)},snapType:'road',road:road.road,roadPoint:{x:road.x,y:road.y},distance:road.distance})}
  if(building){const vx=raw.x-building.x,vy=raw.y-building.y,len=Math.hypot(vx,vy)||1,ux=vx/len,uy=vy/len,of=buildingFootprint(building),support=Math.abs(ux)>Math.abs(uy)?f.halfWidth:f.halfDepth,other=Math.abs(ux)>Math.abs(uy)?of.halfWidth:of.halfDepth;candidates.push({point:{x:building.x+ux*(other+support+12),y:building.y+uy*(other+support+12)},snapType:'building',building,distance:dist(raw,building)})}
  const snap=candidates.sort((a,b)=>a.distance-b.distance)[0],snapped=!!snap&&snap.distance<=58,point=snapped?snap.point:raw,accessPoints=[{side:'north',x:point.x,y:point.y-f.halfDepth,active:false},{side:'east',x:point.x+f.halfWidth,y:point.y,active:false},{side:'south',x:point.x,y:point.y+f.halfDepth,active:false},{side:'west',x:point.x-f.halfWidth,y:point.y,active:false}];
  let connection=null;if(snapped){let best=accessPoints[0],bd=Infinity,target=snap.roadPoint||{x:snap.building.x,y:snap.building.y};for(const a of accessPoints){const d=dist(a,target);if(d<bd){bd=d;best=a}}best.active=true;connection={from:snap.roadPoint||best,to:best};if(snap.snapType==='building')connection.to=buildingConnectionPoint(snap.building,point)}
  return{point,snapType:snapped?snap.snapType:null,road:snap?.road||null,building:snap?.building||null,roadPoint:snap?.roadPoint||null,accessPoints,connection};
}
export function placeBuilding(s,type,x,y){if(canPlaceBuildingAt(s,type,x,y))return false;const b=makeBuilding(type,x,y,newId());b.district=district(x,y);s.cash-=buildingCost(s,type);s.buildings.push(b);return b}
function layoutRandom(s){let seed=Math.max(1,Math.floor(Number(s.gameSeed)||1));seed=(seed*1664525+1013904223)>>>0;s.gameSeed=seed;return seed/4294967296}
export function spawn(s,kind,forced){const pool=TYPES.filter(t=>t.kind===kind&&(!forced||t.name===forced));if(!pool.length)return null;let candidates=pool;if(!forced&&pool.length>1){const recent=s.buildings.slice(-2).map(b=>b.type);const filtered=pool.filter(t=>!recent.includes(t.name));if(filtered.length)candidates=filtered}const type=candidates[Math.floor(layoutRandom(s)*candidates.length)];let x=0,y=0,ok=false;const count=s.buildings.length,minRadius=count<6?170:280,maxRadius=count<6?430:Math.min(760,430+s.companyLevel*22);for(let n=0;n<500&&!ok;n++){const angle=layoutRandom(s)*Math.PI*2,radius=minRadius+layoutRandom(s)*(maxRadius-minRadius);x=Math.cos(angle)*radius+(layoutRandom(s)-.5)*90;y=Math.sin(angle)*radius+(layoutRandom(s)-.5)*90;const river=riverY(x);if(Math.abs(y-river)<105)y+=y<river?-120:120;ok=!canPlaceGeneratedBuilding(s,type,x,y)}if(!ok)return null;const b=makeBuilding(type,x,y,newId());b.district=district(x,y);s.buildings.push(b);return b}
export function repairBuildingLayout(s){const kept=[];for(const b of s.buildings||[]){const type=TYPES.find(t=>t.name===b.type)||{kind:b.kind};const valid=canPlaceGeneratedBuilding({...s,buildings:kept},type,Number(b.x),Number(b.y))===null;if(valid){kept.push(b);continue}let repaired=false;for(let n=0;n<160&&!repaired;n++){const angle=layoutRandom(s)*Math.PI*2,radius=70+layoutRandom(s)*220;const x=Math.max(WORLD_BOUNDS.minX+50,Math.min(WORLD_BOUNDS.maxX-50,Number(b.x)+Math.cos(angle)*radius));const y=Math.max(WORLD_BOUNDS.minY+50,Math.min(WORLD_BOUNDS.maxY-50,Number(b.y)+Math.sin(angle)*radius));if(canPlaceGeneratedBuilding({...s,buildings:kept},type,x,y)===null){b.x=x;b.y=y;b.district=district(x,y);kept.push(b);repaired=true}}}
s.buildings=kept;return s}
export function seed(s){for(const t of['Steel','Food','Parts'])spawn(s,'factory',t);for(const t of['Market','Garage','Builder'])spawn(s,'shop',t)}
export function pointOnRoute(points,t){const total=length(points);if(!total)return points[0];let want=total*Math.max(0,Math.min(1,t)),run=0;for(let i=1;i<points.length;i++){const seg=dist(points[i-1],points[i]);if(run+seg>=want){const q=(want-run)/seg;return{x:points[i-1].x+(points[i].x-points[i-1].x)*q,y:points[i-1].y+(points[i].y-points[i-1].y)*q}}run+=seg}return points.at(-1)}
export function buildingAtPoint(s,p,tolerance=10){if(!finitePoint(p))return null;let best=null,bestDistance=Infinity;for(const b of s.buildings||[]){const hit=buildingHitbox(b,tolerance),dx=Math.max(hit.minX-p.x,0,p.x-hit.maxX),dy=Math.max(hit.minY-p.y,0,p.y-hit.maxY),d=Math.hypot(dx,dy);if(d<=tolerance&&d<bestDistance){best=b;bestDistance=d}}return best}export function nearestBuilding(s,p){return buildingAtPoint(s,p,18)}
const ROAD_BUILDING_SNAP_TOLERANCE=46;
export function roadBuildingTarget(s,p){if(!finitePoint(p))return null;let best=null,bd=Infinity;for(const b of s.buildings||[]){const hit=buildingHitbox(b,ROAD_BUILDING_SNAP_TOLERANCE),dx=Math.max(hit.minX-p.x,0,p.x-hit.maxX),dy=Math.max(hit.minY-p.y,0,p.y-hit.maxY),d=Math.hypot(dx,dy);if(d<bd){bd=d;best=b}}return bd<=ROAD_BUILDING_SNAP_TOLERANCE?best:null}
function projectOnPolyline(points,p){let best=null,run=0;for(let i=1;i<points.length;i++){const q=projectSegment(p,points[i-1],points[i]);if(!best||q.distance<best.distance)best={...q,segment:i-1,along:run+dist(points[i-1],q.point)};run+=dist(points[i-1],points[i])}return best}
export function nearestRoad(s,p){let best=null;for(const road of s.roads||[]){const points=validRoadPoints(road?.points,0);if(!points)continue;const q=projectOnPolyline(points,p);if(q&&(!best||q.distance<best.distance))best={x:q.point.x,y:q.point.y,road,distance:q.distance,segment:q.segment,along:q.along}}return best&&best.distance<=46?best:null}
function buildingFootprintRadius(building){const footprint=buildingFootprint(building);return Math.max(26,(building?.r||25)+9,Math.min(footprint.halfWidth,footprint.halfDepth))}
function buildingDockPoints(building){const x=Number(building?.x)||0,y=Number(building?.y)||0;const specs=building?.kind==='factory'?[{name:'north-loading',x:0,y:31.5,normal:{x:0,y:1},width:22},{name:'south-loading',x:-23.4,y:-31.5,normal:{x:0,y:-1},width:13}]:building?.kind==='warehouse'?[{name:'north-main',x:0,y:33.5,normal:{x:0,y:1},width:24},{name:'north-secondary',x:-30.7,y:33.5,normal:{x:0,y:1},width:14},{name:'south-secondary',x:30.7,y:-33.5,normal:{x:0,y:-1},width:14}]:[{name:'front-entrance',x:0,y:-28.5,normal:{x:0,y:-1},width:12}];return specs.map(dock=>({...dock,point:{x:x+dock.x,y:y+dock.y},approach:{x:x+dock.x+dock.normal.x*10,y:y+dock.y+dock.normal.y*10}}))}
function buildingConnectionPoint(building,target,exteriorOffset=2.5){const dx=Number(target?.x)-Number(building?.x),dy=Number(target?.y)-Number(building?.y),len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len,footprint=buildingFootprint(building),tx=Math.abs(ux)>1e-6?footprint.halfWidth/Math.abs(ux):Infinity,ty=Math.abs(uy)>1e-6?footprint.halfDepth/Math.abs(uy):Infinity,distance=Math.min(tx,ty)+exteriorOffset;return{x:building.x+ux*distance,y:building.y+uy*distance,building,distance:0}}
